-- Example words for word bank
-- Adjectives
insert into public.word_bank (word, type, active) values
  ('silly', 'adjective', true),
  ('sparkly', 'adjective', true),
  ('grumpy', 'adjective', true),
  ('intense', 'adjective', true),
  ('emotional', 'adjective', true),
  ('gloomy', 'adjective', true),
  ('shameless', 'adjective', true),
  ('boring', 'adjective', true),
  ('squishy', 'adjective', true),
  ('strong', 'adjective', true),
  ('serene', 'adjective', true),
  ('impatient', 'adjective', true),
  ('energetic', 'adjective', true),
  ('mysterious', 'adjective', true),
  ('colorful', 'adjective', true),
  ('curious', 'adjective', true),
  ('playful', 'adjective', true),
  ('gigantic', 'adjective', true),
  ('beautiful', 'adjective', true),
  ('charming', 'adjective', true),
  ('unique', 'adjective', true),
  ('tiny', 'adjective', true),
  ('stinky', 'adjective', true),
  ('outlandish', 'adjective', true),
  ('wet', 'adjective', true),
  ('independent', 'adjective', true),
  ('magical', 'adjective', true),
  ('furry', 'adjective', true),
  ('hairy', 'adjective', true),
  ('weak', 'adjective', true),
  ('slippery', 'adjective', true),
  ('inactive', 'adjective', true),
  ('bizarre', 'adjective', true),
  ('fuzzy', 'adjective', true),
  ('filthy', 'adjective', true),
  ('lonely', 'adjective', true),
  ('astute', 'adjective', true),
  ('bouncy', 'adjective', true),
  ('fast', 'adjective', true),
  ('wobbly', 'adjective', true),
  ('eccentric', 'adjective', true),
  ('angry', 'adjective', true),
  ('gorgeous', 'adjective', true),
  ('radiant', 'adjective', true),
  ('popular', 'adjective', true),
  ('shiny', 'adjective', true),
  ('bright', 'adjective', true),
  ('nervous', 'adjective', true),
  ('courageous', 'adjective', true),
  ('gooey', 'adjective', true),
  ('reliable', 'adjective', true),
  ('fluffy', 'adjective', true),
  ('motivated', 'adjective', true),
  ('tall', 'adjective', true),
  ('soft', 'adjective', true),
  ('slow', 'adjective', true),
  ('short', 'adjective', true),
  ('loud', 'adjective', true),
  ('sticky', 'adjective', true),
  ('aromatic', 'adjective', true),
  ('fancy', 'adjective', true),
  ('spooky', 'adjective', true);

-- Nouns
insert into public.word_bank (word, type, active) values
  ('dragon', 'noun', true),
  ('astronaut', 'noun', true),
  ('pickle', 'noun', true),
  ('banana', 'noun', true),
  ('dinosaur', 'noun', true),
  ('cat', 'noun', true),
  ('princess', 'noun', true),
  ('robot', 'noun', true),
  ('ballerina', 'noun', true),
  ('teacher', 'noun', true),
  ('unicorn', 'noun', true),
  ('trampoline', 'noun', true),
  ('clown', 'noun', true),
  ('pair of pants', 'noun', true),
  ('superhero', 'noun', true),
  ('wizard', 'noun', true),
  ('bowl', 'noun', true),
  ('hot dog', 'noun', true),
  ('boat', 'noun', true),
  ('diaper', 'noun', true),
  ('shoe', 'noun', true),
  ('egg', 'noun', true),
  ('rubber ducky', 'noun', true),
  ('trophy', 'noun', true),
  ('laundry basket', 'noun', true),
  ('thermometer', 'noun', true),
  ('sewing machine', 'noun', true),
  ('fern', 'noun', true),
  ('police car', 'noun', true),
  ('filing cabinet', 'noun', true),
  ('crystal ball', 'noun', true),
  ('coin', 'noun', true),
  ('mitten', 'noun', true),
  ('fork', 'noun', true),
  ('egg timer', 'noun', true),
  ('spoon', 'noun', true),
  ('knife', 'noun', true),
  ('rubber ball', 'noun', true),
  ('dump truck', 'noun', true),
  ('tractor', 'noun', true),
  ('water', 'noun', true),
  ('spaceship', 'noun', true),
  ('picture frame', 'noun', true),
  ('hiking boot', 'noun', true),
  ('Christmas tree', 'noun', true),
  ('blanket', 'noun', true),
  ('magic carpet', 'noun', true),
  ('airplane', 'noun', true),
  ('video camera', 'noun', true),
  ('office chair', 'noun', true),
  ('curling iron', 'noun', true),
  ('fire extinguisher', 'noun', true),
  ('truck', 'noun', true),
  ('statue', 'noun', true),
  ('lamp', 'noun', true),
  ('hairbrush', 'noun', true),
  ('toothbrush', 'noun', true),
  ('dirt', 'noun', true),
  ('box', 'noun', true),
  ('raincoat', 'noun', true),
  ('toilet paper', 'noun', true),
  ('bouncy ball', 'noun', true),
  ('flour tortilla', 'noun', true),
  ('candle', 'noun', true),
  ('monster', 'noun', true),
  ('pencil', 'noun', true),
  ('sewing kit', 'noun', true),
  ('cupcake', 'noun', true),
  ('stuffed animal', 'noun', true),
  ('chair', 'noun', true),
  ('notebook', 'noun', true),
  ('mouse', 'noun', true),
  ('paperclip', 'noun', true),
  ('laptop', 'noun', true),
  ('television', 'noun', true),
  ('water bottle', 'noun', true),
  ('tin can', 'noun', true),
  ('swimsuit', 'noun', true),
  ('house', 'noun', true),
  ('toilet bowl', 'noun', true),
  ('guitar', 'noun', true),
  ('bathtub', 'noun', true),
  ('tent', 'noun', true),
  ('can of beans', 'noun', true),
  ('microphone', 'noun', true),
  ('monster truck', 'noun', true),
  ('reindeer', 'noun', true),
  ('brick', 'noun', true),
  ('soccer ball', 'noun', true),
  ('vampire', 'noun', true),
  ('ninja', 'noun', true),
  ('minivan', 'noun', true),
  ('monkey', 'noun', true),
  ('zombie', 'noun', true),
  ('donut', 'noun', true),
  ('snake', 'noun', true),
  ('ice skate', 'noun', true),
  ('hat', 'noun', true),
  ('dragonfly', 'noun', true),
  ('toilet', 'noun', true),
  ('castle', 'noun', true),
  ('alien', 'noun', true);

-- Verbs
insert into public.word_bank (word, type, active) values
  ('dance', 'verb', true),
  ('wiggle', 'verb', true),
  ('explode', 'verb', true),
  ('sneeze', 'verb', true),
  ('jump', 'verb', true),
  ('spin', 'verb', true),
  ('melt', 'verb', true),
  ('bounce', 'verb', true),
  ('fly', 'verb', true),
  ('swim', 'verb', true),
  ('burp', 'verb', true),
  ('run', 'verb', true),
  ('giggle', 'verb', true),
  ('speak', 'verb', true),
  ('eat', 'verb', true),
  ('climb', 'verb', true),
  ('prance', 'verb', true),
  ('bark', 'verb', true),
  ('scratch', 'verb', true),
  ('drink', 'verb', true),
  ('brush', 'verb', true),
  ('meow', 'verb', true),
  ('float', 'verb', true),
  ('slide', 'verb', true),
  ('ponder', 'verb', true),
  ('catch', 'verb', true),
  ('yodel', 'verb', true),
  ('cuddle', 'verb', true),
  ('tighten', 'verb', true),
  ('shuffle', 'verb', true),
  ('practice', 'verb', true),
  ('wrap', 'verb', true),
  ('slice', 'verb', true),
  ('bite', 'verb', true),
  ('dial', 'verb', true),
  ('chat', 'verb', true),
  ('sing', 'verb', true),
  ('slime', 'verb', true),
  ('pounce', 'verb', true),
  ('fall', 'verb', true),
  ('record', 'verb', true),
  ('pay', 'verb', true),
  ('organize', 'verb', true),
  ('dust', 'verb', true),
  ('mow', 'verb', true),
  ('feed', 'verb', true),
  ('clean', 'verb', true),
  ('nibble', 'verb', true),
  ('cook', 'verb', true),
  ('nurture', 'verb', true),
  ('study', 'verb', true),
  ('scream', 'verb', true),
  ('wobble', 'verb', true),
  ('ride', 'verb', true),
  ('purchase', 'verb', true),
  ('sleep', 'verb', true),
  ('design', 'verb', true),
  ('dive', 'verb', true),
  ('throw', 'verb', true),
  ('laugh', 'verb', true),
  ('read', 'verb', true),
  ('watch', 'verb', true),
  ('write', 'verb', true),
  ('hop', 'verb', true),
  ('boil', 'verb', true),
  ('tickle', 'verb', true),
  ('sniff', 'verb', true),
  ('paint', 'verb', true),
  ('zoom', 'verb', true),
  ('freeze', 'verb', true),
  ('crawl', 'verb', true),
  ('fight', 'verb', true),
  ('listen', 'verb', true),
  ('squish', 'verb', true),
  ('morph', 'verb', true),
  ('teleport', 'verb', true);

-- Adverbs
insert into public.word_bank (word, type, active) values
  ('quickly', 'adverb', true),
  ('carefully', 'adverb', true),
  ('slowly', 'adverb', true),
  ('loudly', 'adverb', true),
  ('quietly', 'adverb', true),
  ('awkwardly', 'adverb', true),
  ('gracefully', 'adverb', true),
  ('mysteriously', 'adverb', true),
  ('frantically', 'adverb', true),
  ('energetically', 'adverb', true),
  ('lazily', 'adverb', true),
  ('warmly', 'adverb', true),
  ('silently', 'adverb', true),
  ('enthusiastically', 'adverb', true),
  ('deliberately', 'adverb', true),
  ('dramatically', 'adverb', true),
  ('calmly', 'adverb', true),
  ('wildly', 'adverb', true),
  ('obediently', 'adverb', true),
  ('sneakily', 'adverb', true),
  ('blindly', 'adverb', true),
  ('cheerfully', 'adverb', true),
  ('foolishly', 'adverb', true),
  ('boldly', 'adverb', true),
  ('stupidly', 'adverb', true),
  ('defiantly', 'adverb', true),
  ('softly', 'adverb', true),
  ('eagerly', 'adverb', true),
  ('jealously', 'adverb', true),
  ('smartly', 'adverb', true),
  ('selfishly', 'adverb', true),
  ('deftly', 'adverb', true),
  ('brightly', 'adverb', true),
  ('miserably', 'adverb', true),
  ('gradually', 'adverb', true),
  ('intelligently', 'adverb', true),
  ('sadly', 'adverb', true),
  ('politely', 'adverb', true),
  ('happily', 'adverb', true),
  ('badly', 'adverb', true),
  ('annoyingly', 'adverb', true),
  ('fashionably', 'adverb', true),
  ('negatively', 'adverb', true),
  ('poorly', 'adverb', true),
  ('bravely', 'adverb', true),
  ('honestly', 'adverb', true),
  ('perfectly', 'adverb', true),
  ('angrily', 'adverb', true),
  ('kindly', 'adverb', true),
  ('sharply', 'adverb', true),
  ('innocently', 'adverb', true),
  ('greedily', 'adverb', true),
  ('secretly', 'adverb', true),
  ('elegantly', 'adverb', true),
  ('madly', 'adverb', true),
  ('clumsily', 'adverb', true),
  ('magically', 'adverb', true),
  ('violently', 'adverb', true);

-- Person names
insert into public.word_bank (word, type, active) values
  ('Bob', 'noun-person-name', true),
  ('Princess Sparkles', 'noun-person-name', true),
  ('Dr. Chaos', 'noun-person-name', true),
  ('Captain Awesome', 'noun-person-name', true),
  ('Gary', 'noun-person-name', true),
  ('Principal Jones', 'noun-person-name', true),
  ('Sir Wigglebottom', 'noun-person-name', true),
  ('Robert', 'noun-person-name', true),
  ('Betty', 'noun-person-name', true),
  ('Professor Pickle', 'noun-person-name', true),
  ('Bartholomew', 'noun-person-name', true),
  ('Florence Fluffington', 'noun-person-name', true),
  ('Steve', 'noun-person-name', true),
  ('Queen Banana', 'noun-person-name', true),
  ('Fred', 'noun-person-name', true),
  ('Colonel Mustard', 'noun-person-name', true),
  ('Nancy', 'noun-person-name', true),
  ('Lord Snuggles', 'noun-person-name', true),
  ('Karen', 'noun-person-name', true),
  ('Adam', 'noun-person-name', true),
  ('Elizabeth', 'noun-person-name', true),
  ('Melissa', 'noun-person-name', true),
  ('Juan', 'noun-person-name', true),
  ('Officer Smith', 'noun-person-name', true),
  ('Mary', 'noun-person-name', true),
  ('Cornelius', 'noun-person-name', true),
  ('Nathan', 'noun-person-name', true),
  ('Sergeant Pickles', 'noun-person-name', true),
  ('Duke Noodlesworth', 'noun-person-name', true),
  ('Madame Butterworth', 'noun-person-name', true),
  ('Kevin', 'noun-person-name', true),
  ('Uncle Rico', 'noun-person-name', true),
  ('Patrick', 'noun-person-name', true),
  ('Ricardo', 'noun-person-name', true),
  ('Mrs. Tuneberg', 'noun-person-name', true),
  ('Amanda', 'noun-person-name', true),
  ('Baron Von Fluffypants', 'noun-person-name', true),
  ('Jennifer', 'noun-person-name', true),
  ('Mike', 'noun-person-name', true),
  ('Grandma Ethel', 'noun-person-name', true),
  ('Coach Rodriguez', 'noun-person-name', true),
  ('Uncle Jerry', 'noun-person-name', true),
  ('Aunt Patty', 'noun-person-name', true),
  ('Mr. Jenkins', 'noun-person-name', true),
  ('Mrs. O''Brien', 'noun-person-name', true),
  ('Cousin Larry', 'noun-person-name', true),
  ('Detective Brown', 'noun-person-name', true),
  ('Mayor Thompson', 'noun-person-name', true),
  ('Nurse Rodriguez', 'noun-person-name', true),
  ('Chef Marcel', 'noun-person-name', true),
  ('President Lincoln', 'noun-person-name', true),
  ('General Washington', 'noun-person-name', true),
  ('Doctor Strange', 'noun-person-name', true),
  ('Captain Morgan', 'noun-person-name', true),
  ('Sir Lancelot', 'noun-person-name', true),
  ('King Arthur', 'noun-person-name', true),
  ('Queen Victoria', 'noun-person-name', true),
  ('Duke Wellington', 'noun-person-name', true),
  ('Count Dracula', 'noun-person-name', true),
  ('Lord Voldemort', 'noun-person-name', true),
  ('Darth Vader', 'noun-person-name', true),
  ('Gandalf', 'noun-person-name', true),
  ('Dumbledore', 'noun-person-name', true),
  ('Hermione', 'noun-person-name', true),
  ('Ron', 'noun-person-name', true),
  ('Luke Skywalker', 'noun-person-name', true),
  ('Princess Leia', 'noun-person-name', true),
  ('Frodo', 'noun-person-name', true),
  ('Bilbo', 'noun-person-name', true),
  ('Aragorn', 'noun-person-name', true),
  ('Legolas', 'noun-person-name', true),
  ('Gimli', 'noun-person-name', true),
  ('Superman', 'noun-person-name', true),
  ('Batman', 'noun-person-name', true),
  ('Wonder Woman', 'noun-person-name', true),
  ('Spider-Man', 'noun-person-name', true),
  ('Iron Man', 'noun-person-name', true),
  ('Captain America', 'noun-person-name', true),
  ('Thor', 'noun-person-name', true),
  ('Hulk', 'noun-person-name', true),
  ('Tyler', 'noun-person-name', true),
  ('Black Widow', 'noun-person-name', true),
  ('Sherlock Holmes', 'noun-person-name', true),
  ('Indiana Jones', 'noun-person-name', true),
  ('James Bond', 'noun-person-name', true),
  ('Katniss Everdeen', 'noun-person-name', true),
  ('Harry Potter', 'noun-person-name', true),
  ('Elsa', 'noun-person-name', true),
  ('Anna', 'noun-person-name', true),
  ('Simba', 'noun-person-name', true),
  ('Nemo', 'noun-person-name', true),
  ('Dory', 'noun-person-name', true),
  ('Woody', 'noun-person-name', true),
  ('Buzz Lightyear', 'noun-person-name', true),
  ('Mickey Mouse', 'noun-person-name', true),
  ('Donald Duck', 'noun-person-name', true),
  ('Goofy', 'noun-person-name', true),
  ('Bugs Bunny', 'noun-person-name', true),
  ('Daffy Duck', 'noun-person-name', true),
  ('Porky Pig', 'noun-person-name', true),
  ('SpongeBob', 'noun-person-name', true),
  ('Patrick Star', 'noun-person-name', true),
  ('Squidward', 'noun-person-name', true),
  ('Shrek', 'noun-person-name', true),
  ('Fiona', 'noun-person-name', true),
  ('Mario', 'noun-person-name', true),
  ('Luigi', 'noun-person-name', true),
  ('Princess Peach', 'noun-person-name', true),
  ('Sonic', 'noun-person-name', true),
  ('Pikachu', 'noun-person-name', true),
  ('Ash Ketchum', 'noun-person-name', true),
  ('Link', 'noun-person-name', true),
  ('Zelda', 'noun-person-name', true);

-- Verbs ending in -ing
insert into public.word_bank (word, type, active) values
  ('dancing', 'verb-ending-in-ing', true),
  ('singing', 'verb-ending-in-ing', true),
  ('jumping', 'verb-ending-in-ing', true),
  ('running', 'verb-ending-in-ing', true),
  ('flying', 'verb-ending-in-ing', true),
  ('swimming', 'verb-ending-in-ing', true),
  ('sneezing', 'verb-ending-in-ing', true),
  ('exploding', 'verb-ending-in-ing', true),
  ('wiggling', 'verb-ending-in-ing', true),
  ('diving', 'verb-ending-in-ing', true),
  ('bouncing', 'verb-ending-in-ing', true),
  ('spinning', 'verb-ending-in-ing', true),
  ('melting', 'verb-ending-in-ing', true),
  ('laughing', 'verb-ending-in-ing', true),
  ('crying', 'verb-ending-in-ing', true),
  ('burping', 'verb-ending-in-ing', true),
  ('giggling', 'verb-ending-in-ing', true),
  ('screaming', 'verb-ending-in-ing', true),
  ('wobbling', 'verb-ending-in-ing', true),
  ('floating', 'verb-ending-in-ing', true),
  ('tickling', 'verb-ending-in-ing', true),
  ('teleporting', 'verb-ending-in-ing', true),
  ('kicking', 'verb-ending-in-ing', true),
  ('punching', 'verb-ending-in-ing', true),
  ('waving', 'verb-ending-in-ing', true),
  ('falling', 'verb-ending-in-ing', true),
  ('skipping', 'verb-ending-in-ing', true),
  ('talking', 'verb-ending-in-ing', true),
  ('catching', 'verb-ending-in-ing', true),
  ('throwing', 'verb-ending-in-ing', true),
  ('growing', 'verb-ending-in-ing', true),
  ('cooking', 'verb-ending-in-ing', true),
  ('eating', 'verb-ending-in-ing', true),
  ('drinking', 'verb-ending-in-ing', true),
  ('rolling', 'verb-ending-in-ing', true),
  ('sliding', 'verb-ending-in-ing', true),
  ('cleaning', 'verb-ending-in-ing', true),
  ('sleeping', 'verb-ending-in-ing', true),
  ('working', 'verb-ending-in-ing', true),
  ('purchasing', 'verb-ending-in-ing', true),
  ('recording', 'verb-ending-in-ing', true),
  ('writing', 'verb-ending-in-ing', true),
  ('shopping', 'verb-ending-in-ing', true),
  ('chewing', 'verb-ending-in-ing', true),
  ('drawing', 'verb-ending-in-ing', true),
  ('slicing', 'verb-ending-in-ing', true),
  ('wiping', 'verb-ending-in-ing', true),
  ('brushing', 'verb-ending-in-ing', true),
  ('barking', 'verb-ending-in-ing', true),
  ('meowing', 'verb-ending-in-ing', true),
  ('gathering', 'verb-ending-in-ing', true),
  ('skating', 'verb-ending-in-ing', true),
  ('scrubbing', 'verb-ending-in-ing', true),
  ('practicing', 'verb-ending-in-ing', true),
  ('washing', 'verb-ending-in-ing', true),
  ('skateboarding', 'verb-ending-in-ing', true);

-- Plural nouns
insert into public.word_bank (word, type, active) values
  ('dragons', 'noun-plural', true),
  ('astronauts', 'noun-plural', true),
  ('dinosaurs', 'noun-plural', true),
  ('diapers', 'noun-plural', true),
  ('eggs', 'noun-plural', true),
  ('robots', 'noun-plural', true),
  ('unicorns', 'noun-plural', true),
  ('doors', 'noun-plural', true),
  ('drums', 'noun-plural', true),
  ('shoes', 'noun-plural', true),
  ('tools', 'noun-plural', true),
  ('guitars', 'noun-plural', true),
  ('bottles', 'noun-plural', true),
  ('mailboxes', 'noun-plural', true),
  ('socks', 'noun-plural', true),
  ('houses', 'noun-plural', true),
  ('boats', 'noun-plural', true),
  ('trucks', 'noun-plural', true),
  ('babies', 'noun-plural', true),
  ('wizards', 'noun-plural', true),
  ('voices', 'noun-plural', true),
  ('containers', 'noun-plural', true),
  ('octopuses', 'noun-plural', true),
  ('coins', 'noun-plural', true),
  ('pictures', 'noun-plural', true),
  ('sand castles', 'noun-plural', true),
  ('sandwiches', 'noun-plural', true),
  ('hats', 'noun-plural', true),
  ('bow ties', 'noun-plural', true),
  ('bricks', 'noun-plural', true),
  ('dumpsters', 'noun-plural', true),
  ('shelves', 'noun-plural', true),
  ('spaceships', 'noun-plural', true),
  ('computers', 'noun-plural', true),
  ('penguins', 'noun-plural', true),
  ('museums', 'noun-plural', true),
  ('kittens', 'noun-plural', true),
  ('vampires', 'noun-plural', true),
  ('boxes', 'noun-plural', true),
  ('books', 'noun-plural', true),
  ('ninjas', 'noun-plural', true),
  ('puddles', 'noun-plural', true),
  ('tables', 'noun-plural', true),
  ('bathrooms', 'noun-plural', true),
  ('raindrops', 'noun-plural', true),
  ('clouds', 'noun-plural', true),
  ('bears', 'noun-plural', true),
  ('video games', 'noun-plural', true),
  ('wires', 'noun-plural', true),
  ('paintings', 'noun-plural', true),
  ('chairs', 'noun-plural', true),
  ('synthesizers', 'noun-plural', true),
  ('televisions', 'noun-plural', true),
  ('shirts', 'noun-plural', true),
  ('noodles', 'noun-plural', true),
  ('packages', 'noun-plural', true),
  ('zombies', 'noun-plural', true),
  ('aliens', 'noun-plural', true);

-- Past tense verbs
insert into public.word_bank (word, type, active) values
  ('danced', 'verb-past-tense', true),
  ('wiggled', 'verb-past-tense', true),
  ('exploded', 'verb-past-tense', true),
  ('sneezed', 'verb-past-tense', true),
  ('jumped', 'verb-past-tense', true),
  ('spun', 'verb-past-tense', true),
  ('melted', 'verb-past-tense', true),
  ('bit', 'verb-past-tense', true),
  ('bounced', 'verb-past-tense', true),
  ('tripped', 'verb-past-tense', true),
  ('chewed', 'verb-past-tense', true),
  ('leaped', 'verb-past-tense', true),
  ('flew', 'verb-past-tense', true),
  ('napped', 'verb-past-tense', true),
  ('sliced', 'verb-past-tense', true),
  ('swam', 'verb-past-tense', true),
  ('jogged', 'verb-past-tense', true),
  ('ran', 'verb-past-tense', true),
  ('burped', 'verb-past-tense', true),
  ('fell', 'verb-past-tense', true),
  ('giggled', 'verb-past-tense', true),
  ('punched', 'verb-past-tense', true),
  ('screamed', 'verb-past-tense', true),
  ('wobbled', 'verb-past-tense', true),
  ('zoomed', 'verb-past-tense', true),
  ('squished', 'verb-past-tense', true),
  ('kicked', 'verb-past-tense', true),
  ('floated', 'verb-past-tense', true),
  ('purchased', 'verb-past-tense', true),
  ('bought', 'verb-past-tense', true),
  ('sold', 'verb-past-tense', true),
  ('tickled', 'verb-past-tense', true),
  ('froze', 'verb-past-tense', true),
  ('morphed', 'verb-past-tense', true),
  ('slid', 'verb-past-tense', true),
  ('rolled', 'verb-past-tense', true),
  ('teleported', 'verb-past-tense', true);

-- Body parts
insert into public.word_bank (word, type, active) values
  ('nose', 'body-part', true),
  ('elbow', 'body-part', true),
  ('toe', 'body-part', true),
  ('eyebrow', 'body-part', true),
  ('knee', 'body-part', true),
  ('finger', 'body-part', true),
  ('ear', 'body-part', true),
  ('belly button', 'body-part', true),
  ('ankle', 'body-part', true),
  ('neck', 'body-part', true),
  ('chin', 'body-part', true),
  ('forehead', 'body-part', true),
  ('shoulder', 'body-part', true),
  ('hip', 'body-part', true),
  ('bicep', 'body-part', true),
  ('left leg', 'body-part', true),
  ('right leg', 'body-part', true),
  ('wrist', 'body-part', true),
  ('thumb', 'body-part', true),
  ('eye', 'body-part', true),
  ('knee cap', 'body-part', true),
  ('eyelash', 'body-part', true),
  ('tongue', 'body-part', true),
  ('armpit', 'body-part', true),
  ('pinky finger', 'body-part', true),
  ('nostril', 'body-part', true);

-- Numbers
insert into public.word_bank (word, type, active) values
  ('42', 'number', true),
  ('99', 'number', true),
  ('7', 'number', true),
  ('1,000', 'number', true),
  ('13', 'number', true),
  ('666', 'number', true),
  ('3.14', 'number', true),
  ('100', 'number', true),
  ('21', 'number', true),
  ('500', 'number', true),
  ('77', 'number', true),
  ('4', 'number', true),
  ('68', 'number', true),
  ('1', 'number', true),
  ('2', 'number', true),
  ('3', 'number', true),
  ('5', 'number', true),
  ('6', 'number', true),
  ('8', 'number', true),
  ('9', 'number', true),
  ('10', 'number', true),
  ('1031', 'number', true),
  ('10,000', 'number', true),
  ('1337', 'number', true),
  ('88', 'number', true),
  ('404', 'number', true),
  ('777', 'number', true),
  ('555', 'number', true),
  ('50', 'number', true),
  ('12', 'number', true),
  ('365', 'number', true),
  ('0', 'number', true);

-- Colors
insert into public.word_bank (word, type, active) values
  ('purple', 'color', true),
  ('neon green', 'color', true),
  ('hot pink', 'color', true),
  ('sparkly gold', 'color', true),
  ('rainbow', 'color', true),
  ('midnight blue', 'color', true),
  ('light blue', 'color', true),
  ('dark gray', 'color', true),
  ('white', 'color', true),
  ('black', 'color', true),
  ('orange', 'color', true),
  ('lime green', 'color', true),
  ('turquoise', 'color', true),
  ('cornflower blue', 'color', true),
  ('magenta', 'color', true),
  ('crimson', 'color', true),
  ('electric blue', 'color', true),
  ('silver', 'color', true),
  ('lavender', 'color', true),
  ('chartreuse', 'color', true),
  ('forest green', 'color', true),
  ('burgundy', 'color', true),
  ('dark purple', 'color', true),
  ('cyan', 'color', true),
  ('emerald', 'color', true),
  ('coral', 'color', true),
  ('chrome', 'color', true),
  ('indigo', 'color', true);

-- Animals
insert into public.word_bank (word, type, active) values
  ('llama', 'animal', true),
  ('penguin', 'animal', true),
  ('sloth', 'animal', true),
  ('narwhal', 'animal', true),
  ('camel', 'animal', true),
  ('platypus', 'animal', true),
  ('flamingo', 'animal', true),
  ('hedgehog', 'animal', true),
  ('axolotl', 'animal', true),
  ('centipede', 'animal', true),
  ('clownfish', 'animal', true),
  ('capybara', 'animal', true),
  ('otter', 'animal', true),
  ('baboon', 'animal', true),
  ('beaver', 'animal', true),
  ('cheetah', 'animal', true),
  ('eagle', 'animal', true),
  ('horse', 'animal', true),
  ('panda', 'animal', true),
  ('coyote', 'animal', true),
  ('walrus', 'animal', true),
  ('goat', 'animal', true),
  ('koala', 'animal', true),
  ('pelican', 'animal', true),
  ('polar bear', 'animal', true),
  ('mongoose', 'animal', true),
  ('roadrunner', 'animal', true),
  ('chicken', 'animal', true),
  ('seahorse', 'animal', true),
  ('hippopotamus', 'animal', true),
  ('gorilla', 'animal', true),
  ('pigeon', 'animal', true),
  ('porcupine', 'animal', true),
  ('dolphin', 'animal', true),
  ('ostrich', 'animal', true),
  ('peacock', 'animal', true),
  ('beetle', 'animal', true),
  ('chameleon', 'animal', true),
  ('grizzly bear', 'animal', true),
  ('alligator', 'animal', true),
  ('pig', 'animal', true),
  ('owl', 'animal', true),
  ('earthworm', 'animal', true),
  ('cow', 'animal', true),
  ('parrot', 'animal', true),
  ('house cat', 'animal', true),
  ('frog', 'animal', true),
  ('toad', 'animal', true),
  ('crocodile', 'animal', true),
  ('eel', 'animal', true),
  ('farret', 'animal', true),
  ('donkey', 'animal', true),
  ('fox', 'animal', true),
  ('skunk', 'animal', true),
  ('rattlesnake', 'animal', true),
  ('hyena', 'animal', true),
  ('elephant', 'animal', true),
  ('rabbit', 'animal', true),
  ('racoon', 'animal', true),
  ('meerkat', 'animal', true),
  ('iguana', 'animal', true),
  ('dog', 'animal', true),
  ('scorpion', 'animal', true),
  ('lobster', 'animal', true),
  ('deer', 'animal', true),
  ('chimpanzee', 'animal', true),
  ('hermit crab', 'animal', true),
  ('lion', 'animal', true),
  ('alpaca', 'animal', true),
  ('anteater', 'animal', true),
  ('bobcat', 'animal', true),
  ('leopard', 'animal', true),
  ('armadillo', 'animal', true),
  ('lizard', 'animal', true),
  ('jellyfish', 'animal', true),
  ('great white shark', 'animal', true),
  ('octopus', 'animal', true),
  ('komodo dragon', 'animal', true),
  ('kangaroo', 'animal', true),
  ('pangolin', 'animal', true),
  ('quokka', 'animal', true);

-- Food
insert into public.word_bank (word, type, active) values
  ('pizza', 'food', true),
  ('tacos', 'food', true),
  ('sushi', 'food', true),
  ('donuts', 'food', true),
  ('soup', 'food', true),
  ('nachos', 'food', true),
  ('ice cream', 'food', true),
  ('bacon', 'food', true),
  ('spaghetti', 'food', true),
  ('pickles', 'food', true),
  ('waffles', 'food', true),
  ('enchiladas', 'food', true),
  ('hamburgers', 'food', true),
  ('hot dogs', 'food', true),
  ('chicken nuggets', 'food', true),
  ('burrito', 'food', true),
  ('mac and cheese', 'food', true),
  ('french fries', 'food', true),
  ('chocolate cake', 'food', true),
  ('quesadilla', 'food', true),
  ('popcorn', 'food', true),
  ('ramen', 'food', true),
  ('pancakes', 'food', true),
  ('cookies', 'food', true);

-- Exclamations
insert into public.word_bank (word, type, active) values
  ('Wow', 'exclamation', true),
  ('Yikes', 'exclamation', true),
  ('Ouch', 'exclamation', true),
  ('Holy moly', 'exclamation', true),
  ('Whoops', 'exclamation', true),
  ('Yay', 'exclamation', true),
  ('Uh-oh', 'exclamation', true),
  ('Oh no', 'exclamation', true),
  ('Dang', 'exclamation', true),
  ('Whoa', 'exclamation', true),
  ('LOL', 'exclamation', true),
  ('Zoinks', 'exclamation', true),
  ('Jeepers', 'exclamation', true),
  ('Gadzooks', 'exclamation', true),
  ('Crikey', 'exclamation', true),
  ('Blimey', 'exclamation', true),
  ('Egads', 'exclamation', true),
  ('Golly', 'exclamation', true),
  ('Sheesh', 'exclamation', true),
  ('Yowza', 'exclamation', true),
  ('Yowch', 'exclamation', true),
  ('OMG!', 'exclamation', true),
  ('Bam', 'exclamation', true);

-- Place names
insert into public.word_bank (word, type, active) values
  ('Paris', 'noun-place-name', true),
  ('Tokyo', 'noun-place-name', true),
  ('New York', 'noun-place-name', true),
  ('London', 'noun-place-name', true),
  ('Detroit', 'noun-place-name', true),
  ('Phoenix', 'noun-place-name', true),
  ('San Francisco', 'noun-place-name', true),
  ('Los Angeles', 'noun-place-name', true),
  ('Mount Everest', 'noun-place-name', true),
  ('The Moon', 'noun-place-name', true),
  ('Mars', 'noun-place-name', true),
  ('Toronto', 'noun-place-name', true),
  ('Jupiter', 'noun-place-name', true),
  ('Saturn', 'noun-place-name', true),
  ('Antarctica', 'noun-place-name', true),
  ('Costa Rica', 'noun-place-name', true),
  ('The North Pole', 'noun-place-name', true),
  ('Hawaii', 'noun-place-name', true),
  ('Canada', 'noun-place-name', true),
  ('Atlantis', 'noun-place-name', true),
  ('Berlin', 'noun-place-name', true),
  ('Alaska', 'noun-place-name', true),
  ('Narnia', 'noun-place-name', true),
  ('Stockholm', 'noun-place-name', true),
  ('Mexico', 'noun-place-name', true),
  ('Hogwarts', 'noun-place-name', true),
  ('Mordor', 'noun-place-name', true),
  ('Singapore', 'noun-place-name', true),
  ('Texas', 'noun-place-name', true),
  ('Cleveland', 'noun-place-name', true),
  ('Bolivia', 'noun-place-name', true),
  ('Pluto', 'noun-place-name', true),
  ('Asgard', 'noun-place-name', true),
  ('Valhalla', 'noun-place-name', true),
  ('Wakanda', 'noun-place-name', true),
  ('Gotham City', 'noun-place-name', true),
  ('The Shire', 'noun-place-name', true),
  ('Wonderland', 'noun-place-name', true),
  ('Disneyland', 'noun-place-name', true);

-- Seed a few story templates
insert into public.story_templates (title, template, category, active) values
  (
    'The Great Adventure',
    '{
      "story": "Once upon a time in {0}, there lived a {1} {2} named {3}. Every day, {3} would {4} {5} while {6}. One day, a {7} {8} appeared and challenged {3} to {9}. They traveled to {10} where they found a {11} {12}. In the end, they learned that {13} is the most important thing in life.",
      "placeholders": [
        {"position": 0, "type": "noun-place-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "noun"},
        {"position": 3, "type": "noun-person-name"},
        {"position": 4, "type": "verb"},
        {"position": 5, "type": "adverb"},
        {"position": 6, "type": "verb-ending-in-ing"},
        {"position": 7, "type": "adjective"},
        {"position": 8, "type": "noun"},
        {"position": 9, "type": "verb"},
        {"position": 10, "type": "noun-place-name"},
        {"position": 11, "type": "adjective"},
        {"position": 12, "type": "noun"},
        {"position": 13, "type": "verb-ending-in-ing"}
      ]
    }',
    'adventure',
    true
  ),
  (
    'A Day at School',
    '{
      "story": "It was a {0} morning when {1} walked into the room of our small school in {2}. The teacher, {3}, announced that today they would {4} {5}. Everyone started {6} except for one {7} student who decided to {8} instead. Suddenly, a {9} {10} burst through the door! The whole class began {11} as the principal came running in {12}.",
      "placeholders": [
        {"position": 0, "type": "adjective"},
        {"position": 1, "type": "noun-person-name"},
        {"position": 2, "type": "noun-place-name"},
        {"position": 3, "type": "noun-person-name"},
        {"position": 4, "type": "verb"},
        {"position": 5, "type": "adverb"},
        {"position": 6, "type": "verb-ending-in-ing"},
        {"position": 7, "type": "adjective"},
        {"position": 8, "type": "verb"},
        {"position": 9, "type": "adjective"},
        {"position": 10, "type": "noun"},
        {"position": 11, "type": "verb-ending-in-ing"},
        {"position": 12, "type": "adverb"}
      ]
    }',
    'school',
    true
  ),
  (
    'The Cooking Disaster',
    '{
      "story": "{0}! I just {1} into the kitchen to make my famous {2} recipe. I grabbed {3} {4} from the fridge and started to {5} them {6}. My {7} {8} was watching me {9}, so I tried to impress them by adding {10} cups of {11} {12}. Everything was going great until my {13} started {14}! The whole kitchen turned {15} and smelled like {16}. Never again will I cook with my {17}!",
      "placeholders": [
        {"position": 0, "type": "exclamation"},
        {"position": 1, "type": "verb-past-tense"},
        {"position": 2, "type": "food"},
        {"position": 3, "type": "number"},
        {"position": 4, "type": "noun-plural"},
        {"position": 5, "type": "verb"},
        {"position": 6, "type": "adverb"},
        {"position": 7, "type": "adjective"},
        {"position": 8, "type": "animal"},
        {"position": 9, "type": "adverb"},
        {"position": 10, "type": "number"},
        {"position": 11, "type": "adjective"},
        {"position": 12, "type": "food"},
        {"position": 13, "type": "noun"},
        {"position": 14, "type": "verb-ending-in-ing"},
        {"position": 15, "type": "color"},
        {"position": 16, "type": "noun-plural"},
        {"position": 17, "type": "body-part"}
      ]
    }',
    'cooking',
    true
  ),
  (
    'My Weird Pet',
    '{
      "story": "Last week, I adopted the most {0} pet from the shelter in {1}. It was a {2} {3} with {4} {5} and a {6} {7}. I named them {8}. Every morning, {8} wakes me up by {9} on my {10}. For breakfast, {8} loves to eat {11} covered in {12} {13}. One time, {8} {14} all the way to {15} and came back with {16} {17}. My friends think I''m {18}, but I love my {19} pet!",
      "placeholders": [
        {"position": 0, "type": "adjective"},
        {"position": 1, "type": "noun-place-name"},
        {"position": 2, "type": "color"},
        {"position": 3, "type": "animal"},
        {"position": 4, "type": "adjective"},
        {"position": 5, "type": "body-part"},
        {"position": 6, "type": "adjective"},
        {"position": 7, "type": "body-part"},
        {"position": 8, "type": "noun-person-name"},
        {"position": 9, "type": "verb-ending-in-ing"},
        {"position": 10, "type": "body-part"},
        {"position": 11, "type": "food"},
        {"position": 12, "type": "color"},
        {"position": 13, "type": "food"},
        {"position": 14, "type": "verb-past-tense"},
        {"position": 15, "type": "noun-place-name"},
        {"position": 16, "type": "number"},
        {"position": 17, "type": "noun-plural"},
        {"position": 18, "type": "adjective"},
        {"position": 19, "type": "adjective"}
      ]
    }',
    'pets',
    true
  ),
  (
    'The Family Vacation',
    '{
      "story": "Our family decided to take a {0} vacation to {1}. We packed {2} {3} in our {4} {5} and hit the road. After driving for {6} hours, we finally arrived. The first thing we did was {7} at the {8} beach. My sibling {9} brought their pet {10} who kept {11} everywhere. For dinner, we ate at a restaurant that only served {12} {13}. The waiter, {14}, {15} our food so {16} that it landed on someone''s {17}. {18}! It was the most {19} vacation ever!",
      "placeholders": [
        {"position": 0, "type": "adjective"},
        {"position": 1, "type": "noun-place-name"},
        {"position": 2, "type": "number"},
        {"position": 3, "type": "noun-plural"},
        {"position": 4, "type": "color"},
        {"position": 5, "type": "noun"},
        {"position": 6, "type": "number"},
        {"position": 7, "type": "verb"},
        {"position": 8, "type": "adjective"},
        {"position": 9, "type": "noun-person-name"},
        {"position": 10, "type": "animal"},
        {"position": 11, "type": "verb-ending-in-ing"},
        {"position": 12, "type": "adjective"},
        {"position": 13, "type": "food"},
        {"position": 14, "type": "noun-person-name"},
        {"position": 15, "type": "verb-past-tense"},
        {"position": 16, "type": "adverb"},
        {"position": 17, "type": "body-part"},
        {"position": 18, "type": "exclamation"},
        {"position": 19, "type": "adjective"}
      ]
    }',
    'vacation',
    true
  ),
  (
    'The Science Experiment',
    '{
      "story": "In science class today, {0} and I were partners for a {1} experiment. Professor {2} told us to mix {3} {4} with {5} cups of {6} {7}. We {8} the mixture {9} until it turned {10}. Suddenly, it started {11}! A {12} {13} emerged from the beaker and began to {14} around the classroom. Everyone was {15} and {16} under their desks. The {13} finally stopped when it ate someone''s {17}. Science is {18}!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "noun-person-name"},
        {"position": 3, "type": "number"},
        {"position": 4, "type": "noun-plural"},
        {"position": 5, "type": "number"},
        {"position": 6, "type": "color"},
        {"position": 7, "type": "food"},
        {"position": 8, "type": "verb-past-tense"},
        {"position": 9, "type": "adverb"},
        {"position": 10, "type": "color"},
        {"position": 11, "type": "verb-ending-in-ing"},
        {"position": 12, "type": "adjective"},
        {"position": 13, "type": "animal"},
        {"position": 14, "type": "verb"},
        {"position": 15, "type": "verb-ending-in-ing"},
        {"position": 16, "type": "verb-ending-in-ing"},
        {"position": 17, "type": "noun"},
        {"position": 18, "type": "adjective"}
      ]
    }',
    'science',
    true
  ),
  (
    'The Job Interview',
    '{
      "story": "I walked {0} into the office in {1} for my dream job interview. The interviewer, {2}, asked me to describe myself in {3} words. I said I was {4}, {5}, and really good at {6}. They seemed impressed and asked about my previous experience. I explained how I once {7} {8} {9} in just one day. For my special skill demonstration, I had to {10} while {11} and balancing a {12} on my {13}. They said I was the most {14} candidate they had ever seen. I got the job working with {15} {16}!",
      "placeholders": [
        {"position": 0, "type": "adverb"},
        {"position": 1, "type": "noun-place-name"},
        {"position": 2, "type": "noun-person-name"},
        {"position": 3, "type": "number"},
        {"position": 4, "type": "adjective"},
        {"position": 5, "type": "adjective"},
        {"position": 6, "type": "verb-ending-in-ing"},
        {"position": 7, "type": "verb-past-tense"},
        {"position": 8, "type": "number"},
        {"position": 9, "type": "noun-plural"},
        {"position": 10, "type": "verb"},
        {"position": 11, "type": "verb-ending-in-ing"},
        {"position": 12, "type": "noun"},
        {"position": 13, "type": "body-part"},
        {"position": 14, "type": "adjective"},
        {"position": 15, "type": "adjective"},
        {"position": 16, "type": "noun-plural"}
      ]
    }',
    'work',
    true
  ),
  (
    'The Birthday Party',
    '{
      "story": "It was {0}''s {1}th birthday party in {2}. We decorated everything with {3} balloons and {4} streamers. The birthday cake was shaped like a giant {5} and tasted like {6}. For entertainment, we hired a {7} {8} to {9} for the guests. Everyone played {10} {11} and the winner got {12} {13}. When it was time for presents, {0} opened a box and found a {14} {15} inside that immediately started {16}! The whole party was {17}, and we all {18} until our {19} hurt!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "number"},
        {"position": 2, "type": "noun-place-name"},
        {"position": 3, "type": "color"},
        {"position": 4, "type": "color"},
        {"position": 5, "type": "animal"},
        {"position": 6, "type": "food"},
        {"position": 7, "type": "adjective"},
        {"position": 8, "type": "noun"},
        {"position": 9, "type": "verb"},
        {"position": 10, "type": "adjective"},
        {"position": 11, "type": "noun"},
        {"position": 12, "type": "number"},
        {"position": 13, "type": "noun-plural"},
        {"position": 14, "type": "color"},
        {"position": 15, "type": "animal"},
        {"position": 16, "type": "verb-ending-in-ing"},
        {"position": 17, "type": "adjective"},
        {"position": 18, "type": "verb-past-tense"},
        {"position": 19, "type": "body-part"}
      ]
    }',
    'party',
    true
  ),
  (
    'The Superhero Origin Story',
    '{
      "story": "My name is {0}, and this is how I became the {1} superhero of {2}. It all started when I was {3} at home and a {4} {5} {6} through my window. It bit me on my {7} and I immediately felt {8}. I discovered I could {9} {10} and shoot {11} {12} from my {13}. I made a costume out of {14} {15} and called myself Captain {16}. Now I spend my nights {17} the city from {18} {19}. {20}!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "noun-place-name"},
        {"position": 3, "type": "verb-ending-in-ing"},
        {"position": 4, "type": "color"},
        {"position": 5, "type": "animal"},
        {"position": 6, "type": "verb-past-tense"},
        {"position": 7, "type": "body-part"},
        {"position": 8, "type": "adjective"},
        {"position": 9, "type": "verb"},
        {"position": 10, "type": "adverb"},
        {"position": 11, "type": "adjective"},
        {"position": 12, "type": "noun-plural"},
        {"position": 13, "type": "body-part"},
        {"position": 14, "type": "color"},
        {"position": 15, "type": "noun-plural"},
        {"position": 16, "type": "noun"},
        {"position": 17, "type": "verb-ending-in-ing"},
        {"position": 18, "type": "adjective"},
        {"position": 19, "type": "noun-plural"},
        {"position": 20, "type": "exclamation"}
      ]
    }',
    'superhero',
    true
  ),
  (
    'The Lost Treasure',
    '{
      "story": "Legend says that in {0}, there is a {1} treasure hidden deep inside a {2}. My friend {3} and I decided to find it. We brought {4} {5}, a map, and my pet {6}. After {7} for {8} hours, we discovered a {9} door with {10} {11} carved into it. When we opened it, we found {12} {13} and a note from {14} that said ''{15}! You found my {16} collection!'' We {17} all the way home {18}.",
      "placeholders": [
        {"position": 0, "type": "noun-place-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "noun"},
        {"position": 3, "type": "noun-person-name"},
        {"position": 4, "type": "number"},
        {"position": 5, "type": "noun-plural"},
        {"position": 6, "type": "animal"},
        {"position": 7, "type": "verb-ending-in-ing"},
        {"position": 8, "type": "number"},
        {"position": 9, "type": "color"},
        {"position": 10, "type": "adjective"},
        {"position": 11, "type": "noun-plural"},
        {"position": 12, "type": "number"},
        {"position": 13, "type": "noun-plural"},
        {"position": 14, "type": "noun-person-name"},
        {"position": 15, "type": "exclamation"},
        {"position": 16, "type": "noun"},
        {"position": 17, "type": "verb-past-tense"},
        {"position": 18, "type": "adverb"}
      ]
    }',
    'adventure',
    true
  ),
  (
    'The Camping Trip',
    '{
      "story": "Our scout troop went camping in the forests near {0}. We hiked {1} miles before setting up our {2} tents. That night, we roasted {3} over the campfire and told {4} stories. Suddenly, we heard a {5} sound coming from the {6} bushes. A wild {7} appeared and started {8} our {9}! Counselor {10} tried to {11} it away by {12}, but instead the {7} {13} and joined us around the fire. We fed it some {14} and it became our {15} new friend. Best camping trip ever!",
      "placeholders": [
        {"position": 0, "type": "noun-place-name"},
        {"position": 1, "type": "number"},
        {"position": 2, "type": "color"},
        {"position": 3, "type": "food"},
        {"position": 4, "type": "adjective"},
        {"position": 5, "type": "adjective"},
        {"position": 6, "type": "color"},
        {"position": 7, "type": "animal"},
        {"position": 8, "type": "verb-ending-in-ing"},
        {"position": 9, "type": "noun-plural"},
        {"position": 10, "type": "noun-person-name"},
        {"position": 11, "type": "verb"},
        {"position": 12, "type": "verb-ending-in-ing"},
        {"position": 13, "type": "verb-past-tense"},
        {"position": 14, "type": "food"},
        {"position": 15, "type": "adjective"}
      ]
    }',
    'adventure',
    true
  ),
  (
    'The Substitute Teacher',
    '{
      "story": "Our regular teacher was sick, so we got a substitute named {0}. They walked in wearing a {1} {2} and carrying {3} {4}. For our first lesson, they taught us how to {5} {6} using only our {7}. During recess, {0} {8} on the playground and broke the {9} {10}. In math class, instead of numbers, they made us count {11}. By lunch, everyone was {12} from all the {13}. The principal finally came in and said ''{14}!'' Turns out {0} wasn''t even a real teacher, just a {15} {16} who wandered in!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "color"},
        {"position": 2, "type": "noun"},
        {"position": 3, "type": "number"},
        {"position": 4, "type": "noun-plural"},
        {"position": 5, "type": "verb"},
        {"position": 6, "type": "adverb"},
        {"position": 7, "type": "body-part"},
        {"position": 8, "type": "verb-past-tense"},
        {"position": 9, "type": "adjective"},
        {"position": 10, "type": "noun"},
        {"position": 11, "type": "noun-plural"},
        {"position": 12, "type": "verb-ending-in-ing"},
        {"position": 13, "type": "noun"},
        {"position": 14, "type": "exclamation"},
        {"position": 15, "type": "adjective"},
        {"position": 16, "type": "animal"}
      ]
    }',
    'school',
    true
  ),
  (
    'The Field Trip',
    '{
      "story": "Today our class took a field trip to the {0} museum in {1}. Our guide, {2}, showed us {3} different exhibits about {4} {5}. My best friend {6} accidentally {7} into a display and knocked over a {8} statue of a {9}. The alarm started {10} and {11} security guards came {12}! The museum director was so {13} that their {14} turned {15}. We got kicked out and had to eat lunch in the {16} parking lot while sitting on {17} {18}. At least we still got our {19} gift shop pencils!",
      "placeholders": [
        {"position": 0, "type": "adjective"},
        {"position": 1, "type": "noun-place-name"},
        {"position": 2, "type": "noun-person-name"},
        {"position": 3, "type": "number"},
        {"position": 4, "type": "adjective"},
        {"position": 5, "type": "noun-plural"},
        {"position": 6, "type": "noun-person-name"},
        {"position": 7, "type": "verb-past-tense"},
        {"position": 8, "type": "adjective"},
        {"position": 9, "type": "animal"},
        {"position": 10, "type": "verb-ending-in-ing"},
        {"position": 11, "type": "number"},
        {"position": 12, "type": "adverb"},
        {"position": 13, "type": "adjective"},
        {"position": 14, "type": "body-part"},
        {"position": 15, "type": "color"},
        {"position": 16, "type": "adjective"},
        {"position": 17, "type": "color"},
        {"position": 18, "type": "noun-plural"},
        {"position": 19, "type": "adjective"}
      ]
    }',
    'school',
    true
  ),
  (
    'The Bake Sale Disaster',
    '{
      "story": "I volunteered to make {0} {1} for the school bake sale. I followed {2}''s recipe and mixed {3} cups of {4}, {5} eggs, and a whole jar of {6} {7}. I baked it for {8} minutes until it turned {9}. When I took it out, it was {10} and smelled like {11}. At the bake sale, {12} took one bite and started {13}! Their {14} turned {15} and they {16} {17}. Nobody bought my {1}, but the {18} {19} next door ate the whole thing. Never baking again!",
      "placeholders": [
        {"position": 0, "type": "number"},
        {"position": 1, "type": "food"},
        {"position": 2, "type": "noun-person-name"},
        {"position": 3, "type": "number"},
        {"position": 4, "type": "food"},
        {"position": 5, "type": "number"},
        {"position": 6, "type": "color"},
        {"position": 7, "type": "food"},
        {"position": 8, "type": "number"},
        {"position": 9, "type": "color"},
        {"position": 10, "type": "adjective"},
        {"position": 11, "type": "noun-plural"},
        {"position": 12, "type": "noun-person-name"},
        {"position": 13, "type": "verb-ending-in-ing"},
        {"position": 14, "type": "body-part"},
        {"position": 15, "type": "color"},
        {"position": 16, "type": "verb-past-tense"},
        {"position": 17, "type": "adverb"},
        {"position": 18, "type": "adjective"},
        {"position": 19, "type": "animal"}
      ]
    }',
    'cooking',
    true
  ),
  (
    'The Food Truck',
    '{
      "story": "My cousin {0} started a food truck in {1} that only serves {2} cuisine. Their specialty is {3} {4} topped with {5} {6} and a sprinkle of {7} {8}. I tried it and my {9} immediately felt {10}. The flavor was so {11} that I started {12}! {13} other customers were there, all {14} and {15} with joy. {0} said the secret ingredient is {16} mixed with {17} {18}. Now there''s a {19} hour wait to eat there!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "noun-place-name"},
        {"position": 2, "type": "adjective"},
        {"position": 3, "type": "adjective"},
        {"position": 4, "type": "food"},
        {"position": 5, "type": "color"},
        {"position": 6, "type": "food"},
        {"position": 7, "type": "adjective"},
        {"position": 8, "type": "noun-plural"},
        {"position": 9, "type": "body-part"},
        {"position": 10, "type": "adjective"},
        {"position": 11, "type": "adjective"},
        {"position": 12, "type": "verb-ending-in-ing"},
        {"position": 13, "type": "number"},
        {"position": 14, "type": "verb-ending-in-ing"},
        {"position": 15, "type": "verb-ending-in-ing"},
        {"position": 16, "type": "noun-plural"},
        {"position": 17, "type": "color"},
        {"position": 18, "type": "food"},
        {"position": 19, "type": "number"}
      ]
    }',
    'cooking',
    true
  ),
  (
    'The Talent Show',
    '{
      "story": "I signed up for the school talent show in {0}. My act was {1} while {2} and playing the {3} with my {4}. I practiced for {5} days straight. On the night of the show, I walked on stage wearing my {6} {7} and carrying {8} {9}. Everything was going {10} until a {11} {12} ran onto the stage and started {13}! The audience began {14} as I tried to {15}. Judge {16} held up a score of {17} and said ''{18}!'' I didn''t win, but at least I was {19}!",
      "placeholders": [
        {"position": 0, "type": "noun-place-name"},
        {"position": 1, "type": "verb-ending-in-ing"},
        {"position": 2, "type": "verb-ending-in-ing"},
        {"position": 3, "type": "noun"},
        {"position": 4, "type": "body-part"},
        {"position": 5, "type": "number"},
        {"position": 6, "type": "color"},
        {"position": 7, "type": "noun"},
        {"position": 8, "type": "number"},
        {"position": 9, "type": "noun-plural"},
        {"position": 10, "type": "adverb"},
        {"position": 11, "type": "adjective"},
        {"position": 12, "type": "animal"},
        {"position": 13, "type": "verb-ending-in-ing"},
        {"position": 14, "type": "verb-ending-in-ing"},
        {"position": 15, "type": "verb"},
        {"position": 16, "type": "noun-person-name"},
        {"position": 17, "type": "number"},
        {"position": 18, "type": "exclamation"},
        {"position": 19, "type": "adjective"}
      ]
    }',
    'party',
    true
  ),
  (
    'The Wedding',
    '{
      "story": "I was invited to {0}''s wedding in {1}. The ceremony was held in a {2} {3} decorated with {4} {5} and {6} flowers. The bride wore a {7} dress and the groom wore {8} {9}. During the vows, someone''s pet {10} started {11} {12}. At the reception, we ate {13} {14} and danced the {15}. The DJ, {16}, played music so {17} that everyone''s {18} were {19}! The cake was shaped like a giant {20} and when they cut it, {21} {22} fell out!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "noun-place-name"},
        {"position": 2, "type": "adjective"},
        {"position": 3, "type": "noun"},
        {"position": 4, "type": "color"},
        {"position": 5, "type": "noun-plural"},
        {"position": 6, "type": "color"},
        {"position": 7, "type": "adjective"},
        {"position": 8, "type": "adjective"},
        {"position": 9, "type": "noun-plural"},
        {"position": 10, "type": "animal"},
        {"position": 11, "type": "verb-ending-in-ing"},
        {"position": 12, "type": "adverb"},
        {"position": 13, "type": "adjective"},
        {"position": 14, "type": "food"},
        {"position": 15, "type": "noun"},
        {"position": 16, "type": "noun-person-name"},
        {"position": 17, "type": "adverb"},
        {"position": 18, "type": "body-part"},
        {"position": 19, "type": "verb-ending-in-ing"},
        {"position": 20, "type": "animal"},
        {"position": 21, "type": "number"},
        {"position": 22, "type": "noun-plural"}
      ]
    }',
    'party',
    true
  ),
  (
    'The Zoo Trip',
    '{
      "story": "My family went to the zoo in {0} and it was {1}! First we saw the {2} {3} who were {4}. The zookeeper {5} said they eat {6} {7} for every meal. Next, we visited the {8} exhibit where a {9} {10} tried to {11} my {12}! At the petting zoo, I got to {13} a baby {14} that smelled like {15}. Before we left, we stopped at the gift shop and I bought {16} {17} {18}. Dad {19} on the way to the car and dropped his {20} in the {21} {22} habitat. Best day ever!",
      "placeholders": [
        {"position": 0, "type": "noun-place-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "color"},
        {"position": 3, "type": "animal"},
        {"position": 4, "type": "verb-ending-in-ing"},
        {"position": 5, "type": "noun-person-name"},
        {"position": 6, "type": "number"},
        {"position": 7, "type": "food"},
        {"position": 8, "type": "adjective"},
        {"position": 9, "type": "adjective"},
        {"position": 10, "type": "animal"},
        {"position": 11, "type": "verb"},
        {"position": 12, "type": "noun"},
        {"position": 13, "type": "verb"},
        {"position": 14, "type": "animal"},
        {"position": 15, "type": "noun-plural"},
        {"position": 16, "type": "number"},
        {"position": 17, "type": "adjective"},
        {"position": 18, "type": "noun-plural"},
        {"position": 19, "type": "verb-past-tense"},
        {"position": 20, "type": "noun"},
        {"position": 21, "type": "adjective"},
        {"position": 22, "type": "animal"}
      ]
    }',
    'pets',
    true
  ),
  (
    'The Veterinarian Visit',
    '{
      "story": "I had to take my pet {0} to the vet in {1} because it wouldn''t stop {2}. The vet, Dr. {3}, examined its {4} and said ''{5}! Your {0} has swallowed {6} {7}!'' They had to do surgery using a {8} {9} and {10} {11}. After {12} minutes, they pulled out the {7} plus a {13} {14} we didn''t even know was missing! The bill was {15} dollars. Now my {0} has to take medicine that tastes like {16} and wear a {17} cone on its {18}. At least it''s {19} now!",
      "placeholders": [
        {"position": 0, "type": "animal"},
        {"position": 1, "type": "noun-place-name"},
        {"position": 2, "type": "verb-ending-in-ing"},
        {"position": 3, "type": "noun-person-name"},
        {"position": 4, "type": "body-part"},
        {"position": 5, "type": "exclamation"},
        {"position": 6, "type": "number"},
        {"position": 7, "type": "noun-plural"},
        {"position": 8, "type": "adjective"},
        {"position": 9, "type": "noun"},
        {"position": 10, "type": "color"},
        {"position": 11, "type": "noun-plural"},
        {"position": 12, "type": "number"},
        {"position": 13, "type": "adjective"},
        {"position": 14, "type": "noun"},
        {"position": 15, "type": "number"},
        {"position": 16, "type": "food"},
        {"position": 17, "type": "color"},
        {"position": 18, "type": "body-part"},
        {"position": 19, "type": "adjective"}
      ]
    }',
    'pets',
    true
  ),
  (
    'The Beach Day',
    '{
      "story": "We went to the beach near {0} and it was {1} degrees! I wore my {2} {3} and brought {4} {5}. While building a {6} sandcastle, I found {7} {8} buried in the sand. Suddenly, a {9} wave {10} and {11} everything! A {12} {13} washed up on shore and started {14} toward us. My friend {15} tried to {16} it back to the ocean by {17}, but it just {18} {19}. We decided to {20} home before anything else {21} happened!",
      "placeholders": [
        {"position": 0, "type": "noun-place-name"},
        {"position": 1, "type": "number"},
        {"position": 2, "type": "color"},
        {"position": 3, "type": "noun"},
        {"position": 4, "type": "number"},
        {"position": 5, "type": "noun-plural"},
        {"position": 6, "type": "adjective"},
        {"position": 7, "type": "number"},
        {"position": 8, "type": "noun-plural"},
        {"position": 9, "type": "adjective"},
        {"position": 10, "type": "verb-past-tense"},
        {"position": 11, "type": "verb-past-tense"},
        {"position": 12, "type": "color"},
        {"position": 13, "type": "animal"},
        {"position": 14, "type": "verb-ending-in-ing"},
        {"position": 15, "type": "noun-person-name"},
        {"position": 16, "type": "verb"},
        {"position": 17, "type": "verb-ending-in-ing"},
        {"position": 18, "type": "verb-past-tense"},
        {"position": 19, "type": "adverb"},
        {"position": 20, "type": "verb"},
        {"position": 21, "type": "adjective"}
      ]
    }',
    'vacation',
    true
  ),
  (
    'The Hotel Room',
    '{
      "story": "Our hotel room in {0} was supposed to be {1}, but it was actually {2}! The bed was covered in {3} {4} and smelled like {5}. When I turned on the {6} {7}, {8} {9} fell out! The bathroom had a {10} {11} living in the shower who kept {12}. At night, we could hear the neighbors {13} and playing {14} {15}. Room service brought us {16} instead of the {17} we ordered. The manager {18} offered us {19} dollars off, but we just wanted to {20} out of there!",
      "placeholders": [
        {"position": 0, "type": "noun-place-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "adjective"},
        {"position": 3, "type": "color"},
        {"position": 4, "type": "noun-plural"},
        {"position": 5, "type": "food"},
        {"position": 6, "type": "adjective"},
        {"position": 7, "type": "noun"},
        {"position": 8, "type": "number"},
        {"position": 9, "type": "noun-plural"},
        {"position": 10, "type": "color"},
        {"position": 11, "type": "animal"},
        {"position": 12, "type": "verb-ending-in-ing"},
        {"position": 13, "type": "verb-ending-in-ing"},
        {"position": 14, "type": "adjective"},
        {"position": 15, "type": "noun"},
        {"position": 16, "type": "food"},
        {"position": 17, "type": "food"},
        {"position": 18, "type": "noun-person-name"},
        {"position": 19, "type": "number"},
        {"position": 20, "type": "verb"}
      ]
    }',
    'vacation',
    true
  ),
  (
    'The Chemistry Lab',
    '{
      "story": "In chemistry class, my lab partner {0} and I had to create a {1} reaction. We carefully measured {2} drops of {3} {4} and mixed it with {5} grams of {6} {7}. Professor {8} warned us to {9} {10}, but {0} {11} and added too much! The beaker started {12} and turned {13}. Bubbles shaped like {14} {15} floated everywhere. The smoke detector went off and {16} firefighters showed up. They made us {17} outside while they checked for {18} {19}. We both got detention but at least we passed the experiment!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "number"},
        {"position": 3, "type": "color"},
        {"position": 4, "type": "food"},
        {"position": 5, "type": "number"},
        {"position": 6, "type": "adjective"},
        {"position": 7, "type": "noun-plural"},
        {"position": 8, "type": "noun-person-name"},
        {"position": 9, "type": "verb"},
        {"position": 10, "type": "adverb"},
        {"position": 11, "type": "verb-past-tense"},
        {"position": 12, "type": "verb-ending-in-ing"},
        {"position": 13, "type": "color"},
        {"position": 14, "type": "adjective"},
        {"position": 15, "type": "noun-plural"},
        {"position": 16, "type": "number"},
        {"position": 17, "type": "verb"},
        {"position": 18, "type": "adjective"},
        {"position": 19, "type": "noun-plural"}
      ]
    }',
    'science',
    true
  ),
  (
    'The Robot Invention',
    '{
      "story": "For the science fair, I built a robot in {0} that could {1} automatically. I used {2} {3}, {4} yards of wire, and a {5} {6} for the brain. When I pressed the {7} button, the robot''s {8} started {9} and it began to {10} {11}. Judge {12} was so impressed that their {13} dropped open! But then the robot went {14} and started {15} all the other projects. It {16} {17} {18} before anyone could {19} it. I didn''t win first place, but the local news called me the ''{20} inventor of {0}''!",
      "placeholders": [
        {"position": 0, "type": "noun-place-name"},
        {"position": 1, "type": "verb"},
        {"position": 2, "type": "number"},
        {"position": 3, "type": "noun-plural"},
        {"position": 4, "type": "number"},
        {"position": 5, "type": "color"},
        {"position": 6, "type": "food"},
        {"position": 7, "type": "color"},
        {"position": 8, "type": "body-part"},
        {"position": 9, "type": "verb-ending-in-ing"},
        {"position": 10, "type": "verb"},
        {"position": 11, "type": "adverb"},
        {"position": 12, "type": "noun-person-name"},
        {"position": 13, "type": "body-part"},
        {"position": 14, "type": "adjective"},
        {"position": 15, "type": "verb-ending-in-ing"},
        {"position": 16, "type": "verb-past-tense"},
        {"position": 17, "type": "number"},
        {"position": 18, "type": "noun-plural"},
        {"position": 19, "type": "verb"},
        {"position": 20, "type": "adjective"}
      ]
    }',
    'science',
    true
  ),
  (
    'The First Day of Work',
    '{
      "story": "I was so {0} for my first day working at {1} in {2}. My boss {3} gave me a tour and showed me the {4} {5} where I would be {6}. My first task was to {7} {8} {9} before lunch. I tried to do it {10}, but I accidentally {11} the {12} {13} and everything turned {14}. A customer came in {15} and asked for {16} {17}. I panicked and gave them a {18} instead. By the end of the day, I had {19} so many times that my {20} hurt. Somehow I didn''t get fired!",
      "placeholders": [
        {"position": 0, "type": "adjective"},
        {"position": 1, "type": "noun"},
        {"position": 2, "type": "noun-place-name"},
        {"position": 3, "type": "noun-person-name"},
        {"position": 4, "type": "adjective"},
        {"position": 5, "type": "noun"},
        {"position": 6, "type": "verb-ending-in-ing"},
        {"position": 7, "type": "verb"},
        {"position": 8, "type": "number"},
        {"position": 9, "type": "noun-plural"},
        {"position": 10, "type": "adverb"},
        {"position": 11, "type": "verb-past-tense"},
        {"position": 12, "type": "color"},
        {"position": 13, "type": "noun"},
        {"position": 14, "type": "color"},
        {"position": 15, "type": "adverb"},
        {"position": 16, "type": "number"},
        {"position": 17, "type": "noun-plural"},
        {"position": 18, "type": "animal"},
        {"position": 19, "type": "verb-past-tense"},
        {"position": 20, "type": "body-part"}
      ]
    }',
    'work',
    true
  ),
  (
    'The Office Meeting',
    '{
      "story": "We had a {0} meeting at work today in {1}. The CEO, {2}, walked in carrying {3} {4} and looking very {5}. They announced that our company would now be selling {6} {7} instead of our usual products. Everyone started {8} at once. My coworker {9} stood up and {10} suggested we should {11} to increase sales. The whole room went {12}. Someone''s {13} started {14} and a {15} {16} somehow got into the conference room. The meeting ended when the fire alarm went off because someone tried to {17} {18} in the break room. We all got sent home {19}!",
      "placeholders": [
        {"position": 0, "type": "adjective"},
        {"position": 1, "type": "noun-place-name"},
        {"position": 2, "type": "noun-person-name"},
        {"position": 3, "type": "number"},
        {"position": 4, "type": "noun-plural"},
        {"position": 5, "type": "adjective"},
        {"position": 6, "type": "color"},
        {"position": 7, "type": "noun-plural"},
        {"position": 8, "type": "verb-ending-in-ing"},
        {"position": 9, "type": "noun-person-name"},
        {"position": 10, "type": "adverb"},
        {"position": 11, "type": "verb"},
        {"position": 12, "type": "adjective"},
        {"position": 13, "type": "noun"},
        {"position": 14, "type": "verb-ending-in-ing"},
        {"position": 15, "type": "adjective"},
        {"position": 16, "type": "animal"},
        {"position": 17, "type": "verb"},
        {"position": 18, "type": "food"},
        {"position": 19, "type": "adverb"}
      ]
    }',
    'work',
    true
  ),
  (
    'The Evil Villain',
    '{
      "story": "My superhero nemesis is {0}, the most {1} villain in {2}! They have the power to {3} with their {4} and shoot {5} {6} from their {7}. Their evil lair is hidden inside a {8} {9} filled with {10} {11}. Last night, they tried to steal all the {12} from the city by {13} the main {14}. I arrived just in time and we {15} for {16} minutes. I finally defeated them by {17} my secret weapon - a {18} {19}! They escaped yelling ''{20}! I''ll get you next time!''",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "noun-place-name"},
        {"position": 3, "type": "verb"},
        {"position": 4, "type": "body-part"},
        {"position": 5, "type": "color"},
        {"position": 6, "type": "noun-plural"},
        {"position": 7, "type": "body-part"},
        {"position": 8, "type": "adjective"},
        {"position": 9, "type": "noun"},
        {"position": 10, "type": "number"},
        {"position": 11, "type": "animal"},
        {"position": 12, "type": "food"},
        {"position": 13, "type": "verb-ending-in-ing"},
        {"position": 14, "type": "noun"},
        {"position": 15, "type": "verb-past-tense"},
        {"position": 16, "type": "number"},
        {"position": 17, "type": "verb-ending-in-ing"},
        {"position": 18, "type": "adjective"},
        {"position": 19, "type": "noun"},
        {"position": 20, "type": "exclamation"}
      ]
    }',
    'superhero',
    true
  ),
  (
    'The Sidekick',
    '{
      "story": "Every superhero needs a sidekick, and mine is {0}! They may be {1}, but they have the amazing ability to {2} really {3}. Their costume is made of {4} {5} with a {6} cape. Together, we protect {7} from danger. Last week, we stopped a runaway {8} that was {9} down the street. {0} used their {10} to {11} it before it could {12} into the {13} {14}. The mayor gave us the key to the city made of {15} {16}. We celebrated by eating {17} {18} and {19} until sunrise!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "verb"},
        {"position": 3, "type": "adverb"},
        {"position": 4, "type": "color"},
        {"position": 5, "type": "noun-plural"},
        {"position": 6, "type": "adjective"},
        {"position": 7, "type": "noun-place-name"},
        {"position": 8, "type": "noun"},
        {"position": 9, "type": "verb-ending-in-ing"},
        {"position": 10, "type": "body-part"},
        {"position": 11, "type": "verb"},
        {"position": 12, "type": "verb"},
        {"position": 13, "type": "adjective"},
        {"position": 14, "type": "noun"},
        {"position": 15, "type": "adjective"},
        {"position": 16, "type": "noun-plural"},
        {"position": 17, "type": "number"},
        {"position": 18, "type": "food"},
        {"position": 19, "type": "verb-ending-in-ing"}
      ]
    }',
    'superhero',
    true
  );
