-- Example words for word bank
-- Adjectives
insert into public.word_bank (word, type, active) values
  ('ambient', 'adjective', true),
  ('angry', 'adjective', true),
  ('ample', 'adjective', true),
  ('arduous', 'adjective', true),
  ('aromatic', 'adjective', true),
  ('average', 'adjective', true),
  ('awesome', 'adjective', true),
  ('astute', 'adjective', true),
  ('beautiful', 'adjective', true),
  ('bizarre', 'adjective', true),
  ('boring', 'adjective', true),
  ('bouncy', 'adjective', true),
  ('bright', 'adjective', true),
  ('charming', 'adjective', true),
  ('colorful', 'adjective', true),
  ('courageous', 'adjective', true),
  ('creaky', 'adjective', true),
  ('curious', 'adjective', true),
  ('delinquent', 'adjective', true),
  ('delicate', 'adjective', true),
  ('disruptive', 'adjective', true),
  ('droopy', 'adjective', true),
  ('eccentric', 'adjective', true),
  ('emotional', 'adjective', true),
  ('energetic', 'adjective', true),
  ('explosive', 'adjective', true),
  ('fancy', 'adjective', true),
  ('fast', 'adjective', true),
  ('filthy', 'adjective', true),
  ('fluffy', 'adjective', true),
  ('furry', 'adjective', true),
  ('fuzzy', 'adjective', true),
  ('gigantic', 'adjective', true),
  ('gloomy', 'adjective', true),
  ('gooey', 'adjective', true),
  ('gorgeous', 'adjective', true),
  ('grumpy', 'adjective', true),
  ('hairy', 'adjective', true),
  ('hydraulic', 'adjective', true),
  ('impatient', 'adjective', true),
  ('inactive', 'adjective', true),
  ('independent', 'adjective', true),
  ('intense', 'adjective', true),
  ('lonely', 'adjective', true),
  ('loud', 'adjective', true),
  ('magical', 'adjective', true),
  ('mangled', 'adjective', true),
  ('motivated', 'adjective', true),
  ('mysterious', 'adjective', true),
  ('nervous', 'adjective', true),
  ('outlandish', 'adjective', true),
  ('playful', 'adjective', true),
  ('plump', 'adjective', true),
  ('popular', 'adjective', true),
  ('radiant', 'adjective', true),
  ('reliable', 'adjective', true),
  ('rubbery', 'adjective', true),
  ('serene', 'adjective', true),
  ('shameless', 'adjective', true),
  ('shiny', 'adjective', true),
  ('short', 'adjective', true),
  ('silly', 'adjective', true),
  ('slippery', 'adjective', true),
  ('sloppy', 'adjective', true),
  ('slow', 'adjective', true),
  ('soft', 'adjective', true),
  ('sour', 'adjective', true),
  ('sparkly', 'adjective', true),
  ('spicy', 'adjective', true),
  ('spooky', 'adjective', true),
  ('squishy', 'adjective', true),
  ('sticky', 'adjective', true),
  ('stinky', 'adjective', true),
  ('strong', 'adjective', true),
  ('sweet', 'adjective', true),
  ('tactical', 'adjective', true),
  ('tall', 'adjective', true),
  ('tiny', 'adjective', true),
  ('unique', 'adjective', true),
  ('weak', 'adjective', true),
  ('wet', 'adjective', true),
  ('winged', 'adjective', true),
  ('wobbly', 'adjective', true);

-- Nouns
insert into public.word_bank (word, type, active) values
  ('Christmas tree', 'noun', true),
  ('adventure', 'noun', true),
  ('airplane', 'noun', true),
  ('alarm clock', 'noun', true),
  ('alien', 'noun', true),
  ('aquarium', 'noun', true),
  ('art', 'noun', true),
  ('astronaut', 'noun', true),
  ('baby', 'noun', true),
  ('backyard', 'noun', true),
  ('bag', 'noun', true),
  ('ball', 'noun', true),
  ('ballerina', 'noun', true),
  ('bandage', 'noun', true),
  ('bank', 'noun', true),
  ('baseball', 'noun', true),
  ('basketball', 'noun', true),
  ('bathroom', 'noun', true),
  ('bathtub', 'noun', true),
  ('bed', 'noun', true),
  ('bedroom', 'noun', true),
  ('bell', 'noun', true),
  ('belt buckle', 'noun', true),
  ('bicycle', 'noun', true),
  ('bird feeder', 'noun', true),
  ('blanket', 'noun', true),
  ('boat', 'noun', true),
  ('book', 'noun', true),
  ('bottle', 'noun', true),
  ('bouncy ball', 'noun', true),
  ('bowl', 'noun', true),
  ('bowling ball', 'noun', true),
  ('box', 'noun', true),
  ('brick', 'noun', true),
  ('broom', 'noun', true),
  ('calculator', 'noun', true),
  ('calendar', 'noun', true),
  ('camera', 'noun', true),
  ('candle', 'noun', true),
  ('canoe', 'noun', true),
  ('castle', 'noun', true),
  ('chair', 'noun', true),
  ('clock', 'noun', true),
  ('clown', 'noun', true),
  ('coin', 'noun', true),
  ('computer', 'noun', true),
  ('cook book', 'noun', true),
  ('cowboy boot', 'noun', true),
  ('cowboy hat', 'noun', true),
  ('crystal ball', 'noun', true),
  ('curling iron', 'noun', true),
  ('database', 'noun', true),
  ('desk', 'noun', true),
  ('destiny', 'noun', true),
  ('diaper', 'noun', true),
  ('dictionary', 'noun', true),
  ('dinner', 'noun', true),
  ('dinosaur', 'noun', true),
  ('dirt', 'noun', true),
  ('drum', 'noun', true),
  ('dump truck', 'noun', true),
  ('dumpster', 'noun', true),
  ('earthquake', 'noun', true),
  ('egg timer', 'noun', true),
  ('elevator', 'noun', true),
  ('engine', 'noun', true),
  ('fabric', 'noun', true),
  ('factory', 'noun', true),
  ('fame', 'noun', true),
  ('farmer', 'noun', true),
  ('fern', 'noun', true),
  ('filing cabinet', 'noun', true),
  ('fire extinguisher', 'noun', true),
  ('fork', 'noun', true),
  ('game', 'noun', true),
  ('garbage dump', 'noun', true),
  ('garden', 'noun', true),
  ('ghost', 'noun', true),
  ('gift', 'noun', true),
  ('glass', 'noun', true),
  ('glove', 'noun', true),
  ('grass', 'noun', true),
  ('guitar', 'noun', true),
  ('hairbrush', 'noun', true),
  ('hat', 'noun', true),
  ('hiking boot', 'noun', true),
  ('history', 'noun', true),
  ('hospital', 'noun', true),
  ('house', 'noun', true),
  ('ice skate', 'noun', true),
  ('icicle', 'noun', true),
  ('igloo', 'noun', true),
  ('island', 'noun', true),
  ('kaleidoscope', 'noun', true),
  ('karaoke', 'noun', true),
  ('kayak', 'noun', true),
  ('keyboard', 'noun', true),
  ('king', 'noun', true),
  ('kiosk', 'noun', true),
  ('kitchen', 'noun', true),
  ('kite', 'noun', true),
  ('knife', 'noun', true),
  ('lake', 'noun', true),
  ('lamp', 'noun', true),
  ('laptop', 'noun', true),
  ('laser beam', 'noun', true),
  ('laundry basket', 'noun', true),
  ('library', 'noun', true),
  ('literature', 'noun', true),
  ('magazine', 'noun', true),
  ('magic carpet', 'noun', true),
  ('magnet', 'noun', true),
  ('mailbox', 'noun', true),
  ('map', 'noun', true),
  ('microphone', 'noun', true),
  ('minivan', 'noun', true),
  ('mirror', 'noun', true),
  ('mitten', 'noun', true),
  ('monster truck', 'noun', true),
  ('monster', 'noun', true),
  ('motor', 'noun', true),
  ('motorcycle', 'noun', true),
  ('mousepad', 'noun', true),
  ('music', 'noun', true),
  ('napkin', 'noun', true),
  ('necklace', 'noun', true),
  ('newspaper', 'noun', true),
  ('ninja', 'noun', true),
  ('notebook', 'noun', true),
  ('office chair', 'noun', true),
  ('oven', 'noun', true),
  ('oxygen', 'noun', true),
  ('package', 'noun', true),
  ('pair of pants', 'noun', true),
  ('paper', 'noun', true),
  ('paperclip', 'noun', true),
  ('pearl', 'noun', true),
  ('pencil', 'noun', true),
  ('photo', 'noun', true),
  ('piano', 'noun', true),
  ('pickup truck', 'noun', true),
  ('picture frame', 'noun', true),
  ('planet', 'noun', true),
  ('police car', 'noun', true),
  ('princess', 'noun', true),
  ('prize', 'noun', true),
  ('quagmire', 'noun', true),
  ('queen', 'noun', true),
  ('quest', 'noun', true),
  ('radiation', 'noun', true),
  ('raincoat', 'noun', true),
  ('recipe', 'noun', true),
  ('refrigerator', 'noun', true),
  ('river', 'noun', true),
  ('road', 'noun', true),
  ('robot', 'noun', true),
  ('rubber ball', 'noun', true),
  ('rubber ducky', 'noun', true),
  ('ruler', 'noun', true),
  ('sauce', 'noun', true),
  ('sewing kit', 'noun', true),
  ('sewing machine', 'noun', true),
  ('shirt', 'noun', true),
  ('shoe', 'noun', true),
  ('silk', 'noun', true),
  ('sleeping bag', 'noun', true),
  ('snowflake', 'noun', true),
  ('soap', 'noun', true),
  ('soccer ball', 'noun', true),
  ('software', 'noun', true),
  ('spaceship', 'noun', true),
  ('spoon', 'noun', true),
  ('statue', 'noun', true),
  ('stone', 'noun', true),
  ('story', 'noun', true),
  ('stuffed animal', 'noun', true),
  ('synthesizer', 'noun', true),
  ('superhero', 'noun', true),
  ('swimsuit', 'noun', true),
  ('table', 'noun', true),
  ('tablecloth', 'noun', true),
  ('talent', 'noun', true),
  ('tattoo', 'noun', true),
  ('tea cup', 'noun', true),
  ('tea pot', 'noun', true),
  ('teacher', 'noun', true),
  ('telephone', 'noun', true),
  ('television', 'noun', true),
  ('tennis ball', 'noun', true),
  ('tennis racket', 'noun', true),
  ('tent', 'noun', true),
  ('tentacle', 'noun', true),
  ('thermometer', 'noun', true),
  ('tin can', 'noun', true),
  ('toaster', 'noun', true),
  ('toilet bowl', 'noun', true),
  ('toilet paper', 'noun', true),
  ('toilet', 'noun', true),
  ('toothbrush', 'noun', true),
  ('top hat', 'noun', true),
  ('towel', 'noun', true),
  ('tower', 'noun', true),
  ('tractor', 'noun', true),
  ('trampoline', 'noun', true),
  ('trash can', 'noun', true),
  ('tree', 'noun', true),
  ('trophy', 'noun', true),
  ('truck', 'noun', true),
  ('umbrella', 'noun', true),
  ('underwear', 'noun', true),
  ('unicorn', 'noun', true),
  ('unicycle', 'noun', true),
  ('vacuum cleaner', 'noun', true),
  ('vampire', 'noun', true),
  ('van', 'noun', true),
  ('vault', 'noun', true),
  ('video camera', 'noun', true),
  ('village', 'noun', true),
  ('volcano', 'noun', true),
  ('wagon', 'noun', true),
  ('wallet', 'noun', true),
  ('water bottle', 'noun', true),
  ('water', 'noun', true),
  ('window', 'noun', true),
  ('wisdom', 'noun', true),
  ('wizard', 'noun', true),
  ('wood', 'noun', true),
  ('yacht', 'noun', true),
  ('yard', 'noun', true),
  ('yarn', 'noun', true),
  ('zeppelin', 'noun', true),
  ('zipper', 'noun', true),
  ('zombie', 'noun', true),
  ('zoo', 'noun', true);

-- Verbs
insert into public.word_bank (word, type, active) values
  ('accelerate', 'verb', true),
  ('adapt', 'verb', true),
  ('adore', 'verb', true),
  ('bark', 'verb', true),
  ('bite', 'verb', true),
  ('boil', 'verb', true),
  ('bounce', 'verb', true),
  ('brush', 'verb', true),
  ('buckle', 'verb', true),
  ('burp', 'verb', true),
  ('burst', 'verb', true),
  ('catch', 'verb', true),
  ('chat', 'verb', true),
  ('clean', 'verb', true),
  ('climb', 'verb', true),
  ('close', 'verb', true),
  ('control', 'verb', true),
  ('cook', 'verb', true),
  ('cover', 'verb', true),
  ('crawl', 'verb', true),
  ('cuddle', 'verb', true),
  ('dance', 'verb', true),
  ('deliver', 'verb', true),
  ('demolish', 'verb', true),
  ('design', 'verb', true),
  ('dial', 'verb', true),
  ('disrupt', 'verb', true),
  ('distract', 'verb', true),
  ('dive', 'verb', true),
  ('drink', 'verb', true),
  ('dust', 'verb', true),
  ('eat', 'verb', true),
  ('enchant', 'verb', true),
  ('evolve', 'verb', true),
  ('explode', 'verb', true),
  ('fall', 'verb', true),
  ('feed', 'verb', true),
  ('fight', 'verb', true),
  ('float', 'verb', true),
  ('fly', 'verb', true),
  ('freeze', 'verb', true),
  ('gargle', 'verb', true),
  ('giggle', 'verb', true),
  ('give', 'verb', true),
  ('greet', 'verb', true),
  ('grow', 'verb', true),
  ('hack', 'verb', true),
  ('haul', 'verb', true),
  ('heal', 'verb', true),
  ('help', 'verb', true),
  ('hire', 'verb', true),
  ('hold', 'verb', true),
  ('hop', 'verb', true),
  ('hustle', 'verb', true),
  ('imagine', 'verb', true),
  ('imitate', 'verb', true),
  ('implement', 'verb', true),
  ('isolate', 'verb', true),
  ('jiggle', 'verb', true),
  ('jog', 'verb', true),
  ('jump', 'verb', true),
  ('laugh', 'verb', true),
  ('launch', 'verb', true),
  ('leak', 'verb', true),
  ('learn', 'verb', true),
  ('lease', 'verb', true),
  ('leave', 'verb', true),
  ('like', 'verb', true),
  ('listen', 'verb', true),
  ('love', 'verb', true),
  ('magnify', 'verb', true),
  ('manage', 'verb', true),
  ('melt', 'verb', true),
  ('mentor', 'verb', true),
  ('meow', 'verb', true),
  ('mingle', 'verb', true),
  ('morph', 'verb', true),
  ('motivate', 'verb', true),
  ('move', 'verb', true),
  ('mow', 'verb', true),
  ('multiply', 'verb', true),
  ('nag', 'verb', true),
  ('neglect', 'verb', true),
  ('negotiate', 'verb', true),
  ('nibble', 'verb', true),
  ('nourish', 'verb', true),
  ('nurture', 'verb', true),
  ('observe', 'verb', true),
  ('offend', 'verb', true),
  ('open', 'verb', true),
  ('organize', 'verb', true),
  ('oscillate', 'verb', true),
  ('overload', 'verb', true),
  ('pack', 'verb', true),
  ('paint', 'verb', true),
  ('pamper', 'verb', true),
  ('pay', 'verb', true),
  ('perform', 'verb', true),
  ('pick', 'verb', true),
  ('plan', 'verb', true),
  ('play', 'verb', true),
  ('ponder', 'verb', true),
  ('pounce', 'verb', true),
  ('practice', 'verb', true),
  ('prance', 'verb', true),
  ('purchase', 'verb', true),
  ('quack', 'verb', true),
  ('quarantine', 'verb', true),
  ('quit', 'verb', true),
  ('race', 'verb', true),
  ('radiate', 'verb', true),
  ('rattle', 'verb', true),
  ('reach', 'verb', true),
  ('read', 'verb', true),
  ('record', 'verb', true),
  ('rejuvenate', 'verb', true),
  ('ride', 'verb', true),
  ('roll', 'verb', true),
  ('rub', 'verb', true),
  ('run', 'verb', true),
  ('sail', 'verb', true),
  ('salute', 'verb', true),
  ('scratch', 'verb', true),
  ('scream', 'verb', true),
  ('scrub', 'verb', true),
  ('search', 'verb', true),
  ('shine', 'verb', true),
  ('shrink', 'verb', true),
  ('shuffle', 'verb', true),
  ('sing', 'verb', true),
  ('sleep', 'verb', true),
  ('slice', 'verb', true),
  ('slide', 'verb', true),
  ('slime', 'verb', true),
  ('sneeze', 'verb', true),
  ('sniff', 'verb', true),
  ('speak', 'verb', true),
  ('spin', 'verb', true),
  ('spray', 'verb', true),
  ('squash', 'verb', true),
  ('study', 'verb', true),
  ('subtract', 'verb', true),
  ('swallow', 'verb', true),
  ('swim', 'verb', true),
  ('tailor', 'verb', true),
  ('take', 'verb', true),
  ('taste', 'verb', true),
  ('teach', 'verb', true),
  ('tease', 'verb', true),
  ('teleport', 'verb', true),
  ('throw', 'verb', true),
  ('tickle', 'verb', true),
  ('tighten', 'verb', true),
  ('toss', 'verb', true),
  ('travel', 'verb', true),
  ('uncover', 'verb', true),
  ('unlock', 'verb', true),
  ('unwind', 'verb', true),
  ('upgrade', 'verb', true),
  ('validate', 'verb', true),
  ('vaporize', 'verb', true),
  ('walk', 'verb', true),
  ('wander', 'verb', true),
  ('warp', 'verb', true),
  ('wash', 'verb', true),
  ('watch', 'verb', true),
  ('whisper', 'verb', true),
  ('wiggle', 'verb', true),
  ('wobble', 'verb', true),
  ('wrap', 'verb', true),
  ('write', 'verb', true),
  ('yank', 'verb', true),
  ('yawn', 'verb', true),
  ('yell', 'verb', true),
  ('yodel', 'verb', true),
  ('zoom', 'verb', true);

-- Adverbs
insert into public.word_bank (word, type, active) values
  ('abnormally', 'adverb', true),
  ('abruptly', 'adverb', true),
  ('angrily', 'adverb', true),
  ('annoyingly', 'adverb', true),
  ('awkwardly', 'adverb', true),
  ('badly', 'adverb', true),
  ('blindly', 'adverb', true),
  ('boldly', 'adverb', true),
  ('bravely', 'adverb', true),
  ('brightly', 'adverb', true),
  ('calmly', 'adverb', true),
  ('carefully', 'adverb', true),
  ('cheerfully', 'adverb', true),
  ('clumsily', 'adverb', true),
  ('defiantly', 'adverb', true),
  ('deftly', 'adverb', true),
  ('deliberately', 'adverb', true),
  ('dramatically', 'adverb', true),
  ('eagerly', 'adverb', true),
  ('easily', 'adverb', true),
  ('elegantly', 'adverb', true),
  ('energetically', 'adverb', true),
  ('enthusiastically', 'adverb', true),
  ('fashionably', 'adverb', true),
  ('favorably', 'adverb', true),
  ('foolishly', 'adverb', true),
  ('frantically', 'adverb', true),
  ('freely', 'adverb', true),
  ('gladly', 'adverb', true),
  ('gleefully', 'adverb', true),
  ('gloriously', 'adverb', true),
  ('gracefully', 'adverb', true),
  ('gradually', 'adverb', true),
  ('greedily', 'adverb', true),
  ('happily', 'adverb', true),
  ('honestly', 'adverb', true),
  ('hopelessly', 'adverb', true),
  ('humbly', 'adverb', true),
  ('innocently', 'adverb', true),
  ('intelligently', 'adverb', true),
  ('intentionally', 'adverb', true),
  ('jealously', 'adverb', true),
  ('joyfully', 'adverb', true),
  ('jubilantly', 'adverb', true),
  ('judiciously', 'adverb', true),
  ('keenly', 'adverb', true),
  ('kindly', 'adverb', true),
  ('lawfully', 'adverb', true),
  ('lazily', 'adverb', true),
  ('loudly', 'adverb', true),
  ('madly', 'adverb', true),
  ('magically', 'adverb', true),
  ('magnetically', 'adverb', true),
  ('miserably', 'adverb', true),
  ('mysteriously', 'adverb', true),
  ('naively', 'adverb', true),
  ('naturally', 'adverb', true),
  ('neatly', 'adverb', true),
  ('negatively', 'adverb', true),
  ('notably', 'adverb', true),
  ('obediently', 'adverb', true),
  ('objectively', 'adverb', true),
  ('occasionally', 'adverb', true),
  ('openly', 'adverb', true),
  ('organically', 'adverb', true),
  ('overwhelmingly', 'adverb', true),
  ('perfectly', 'adverb', true),
  ('politely', 'adverb', true),
  ('poorly', 'adverb', true),
  ('positively', 'adverb', true),
  ('powerfully', 'adverb', true),
  ('proactively', 'adverb', true),
  ('quaintly', 'adverb', true),
  ('quickly', 'adverb', true),
  ('quietly', 'adverb', true),
  ('rationally', 'adverb', true),
  ('readily', 'adverb', true),
  ('reassuringly', 'adverb', true),
  ('sadly', 'adverb', true),
  ('secretly', 'adverb', true),
  ('selfishly', 'adverb', true),
  ('sharply', 'adverb', true),
  ('silently', 'adverb', true),
  ('skillfully', 'adverb', true),
  ('slowly', 'adverb', true),
  ('smartly', 'adverb', true),
  ('sneakily', 'adverb', true),
  ('softly', 'adverb', true),
  ('steadily', 'adverb', true),
  ('stupidly', 'adverb', true),
  ('sweetly', 'adverb', true),
  ('swiftly', 'adverb', true),
  ('temporarily', 'adverb', true),
  ('tenaciously', 'adverb', true),
  ('thankfully', 'adverb', true),
  ('triumphantly', 'adverb', true),
  ('ultimately', 'adverb', true),
  ('ultrasonically', 'adverb', true),
  ('unabashedly', 'adverb', true),
  ('unambiguously', 'adverb', true),
  ('unanimously', 'adverb', true),
  ('vacantly', 'adverb', true),
  ('victoriously', 'adverb', true),
  ('violently', 'adverb', true),
  ('warmly', 'adverb', true),
  ('wastefully', 'adverb', true),
  ('weakly', 'adverb', true),
  ('wildly', 'adverb', true),
  ('willingly', 'adverb', true),
  ('youthfully', 'adverb', true),
  ('zestfully', 'adverb', true);

-- Person names
insert into public.word_bank (word, type, active) values
  ('Adam', 'noun-person-name', true),
  ('Alibaster Juniper III', 'noun-person-name', true),
  ('Amanda', 'noun-person-name', true),
  ('Anna', 'noun-person-name', true),
  ('Aragorn', 'noun-person-name', true),
  ('Atticus Finch', 'noun-person-name', true),
  ('Aunt Patty', 'noun-person-name', true),
  ('Baron Von Fluffypants', 'noun-person-name', true),
  ('Bartholomew', 'noun-person-name', true),
  ('Batman', 'noun-person-name', true),
  ('Ben Franklin', 'noun-person-name', true),
  ('Betty', 'noun-person-name', true),
  ('Bilbo', 'noun-person-name', true),
  ('Bill', 'noun-person-name', true),
  ('Bob', 'noun-person-name', true),
  ('Brad', 'noun-person-name', true),
  ('Bugs Bunny', 'noun-person-name', true),
  ('Buzz Lightyear', 'noun-person-name', true),
  ('Captain America', 'noun-person-name', true),
  ('Captain Awesome', 'noun-person-name', true),
  ('Captain Morgan', 'noun-person-name', true),
  ('Chad', 'noun-person-name', true),
  ('Chef Marcel', 'noun-person-name', true),
  ('Coach Rodriguez', 'noun-person-name', true),
  ('Colonel Mustard', 'noun-person-name', true),
  ('Cornelius', 'noun-person-name', true),
  ('Count Dracula', 'noun-person-name', true),
  ('Cousin Larry', 'noun-person-name', true),
  ('Cowboy Dan', 'noun-person-name', true),
  ('Dave', 'noun-person-name', true),
  ('Daffy Duck', 'noun-person-name', true),
  ('Darth Vader', 'noun-person-name', true),
  ('Detective Brown', 'noun-person-name', true),
  ('Doctor Strange', 'noun-person-name', true),
  ('Donald Duck', 'noun-person-name', true),
  ('Dory', 'noun-person-name', true),
  ('Dr. Chaos', 'noun-person-name', true),
  ('Duke Noodlesworth', 'noun-person-name', true),
  ('Duke Wellington', 'noun-person-name', true),
  ('Dumbledore', 'noun-person-name', true),
  ('Ebenezer Scrooge', 'noun-person-name', true),
  ('Elizabeth', 'noun-person-name', true),
  ('Elmer Fudd', 'noun-person-name', true),
  ('Elsa', 'noun-person-name', true),
  ('Ernest', 'noun-person-name', true),
  ('Finn', 'noun-person-name', true),
  ('Fiona', 'noun-person-name', true),
  ('Florence Fluffington', 'noun-person-name', true),
  ('Fred', 'noun-person-name', true),
  ('Frodo', 'noun-person-name', true),
  ('Gandalf', 'noun-person-name', true),
  ('Gary', 'noun-person-name', true),
  ('General Washington', 'noun-person-name', true),
  ('Gimli', 'noun-person-name', true),
  ('Goofy', 'noun-person-name', true),
  ('Grandma Ethel', 'noun-person-name', true),
  ('Harold', 'noun-person-name', true),
  ('Harry Potter', 'noun-person-name', true),
  ('Hermione', 'noun-person-name', true),
  ('Hulk', 'noun-person-name', true),
  ('Indiana Jones', 'noun-person-name', true),
  ('Iron Man', 'noun-person-name', true),
  ('Jack', 'noun-person-name', true),
  ('Jake', 'noun-person-name', true),
  ('James Bond', 'noun-person-name', true),
  ('Jennifer', 'noun-person-name', true),
  ('Juan', 'noun-person-name', true),
  ('Karen', 'noun-person-name', true),
  ('Katniss Everdeen', 'noun-person-name', true),
  ('Kevin', 'noun-person-name', true),
  ('King Arthur', 'noun-person-name', true),
  ('Legolas', 'noun-person-name', true),
  ('Link', 'noun-person-name', true),
  ('Lord Farquaad', 'noun-person-name', true),
  ('Lord Voldemort', 'noun-person-name', true),
  ('Luigi', 'noun-person-name', true),
  ('Luke Skywalker', 'noun-person-name', true),
  ('Madame Butterworth', 'noun-person-name', true),
  ('Mario', 'noun-person-name', true),
  ('Mary', 'noun-person-name', true),
  ('Mayor Thompson', 'noun-person-name', true),
  ('Melissa', 'noun-person-name', true),
  ('Mickey Mouse', 'noun-person-name', true),
  ('Mike', 'noun-person-name', true),
  ('Mr. Jenkins', 'noun-person-name', true),
  ('Mrs. O''Brien', 'noun-person-name', true),
  ('Mrs. Tuneberg', 'noun-person-name', true),
  ('Nancy', 'noun-person-name', true),
  ('Nathan', 'noun-person-name', true),
  ('Nemo', 'noun-person-name', true),
  ('Nurse Rodriguez', 'noun-person-name', true),
  ('Officer Smith', 'noun-person-name', true),
  ('Patrick Star', 'noun-person-name', true),
  ('Patrick', 'noun-person-name', true),
  ('Pikachu', 'noun-person-name', true),
  ('Porky Pig', 'noun-person-name', true),
  ('President Lincoln', 'noun-person-name', true),
  ('Princess Bubblegum', 'noun-person-name', true),
  ('Princess Leia', 'noun-person-name', true),
  ('Princess Peach', 'noun-person-name', true),
  ('Princess Sparkles', 'noun-person-name', true),
  ('Principal Jones', 'noun-person-name', true),
  ('Professor Pickle', 'noun-person-name', true),
  ('Queen Banana', 'noun-person-name', true),
  ('Queen Victoria', 'noun-person-name', true),
  ('Ricardo', 'noun-person-name', true),
  ('Robert', 'noun-person-name', true),
  ('Ron', 'noun-person-name', true),
  ('Rumplestiltskin', 'noun-person-name', true),
  ('Señor Snuggles', 'noun-person-name', true),
  ('Sergeant Pickles', 'noun-person-name', true),
  ('Sherlock Holmes', 'noun-person-name', true),
  ('Shrek', 'noun-person-name', true),
  ('Simba', 'noun-person-name', true),
  ('Sir Lancelot', 'noun-person-name', true),
  ('Sir Wigglebottom', 'noun-person-name', true),
  ('Spider-Man', 'noun-person-name', true),
  ('SpongeBob', 'noun-person-name', true),
  ('Squidward', 'noun-person-name', true),
  ('Sterling Archer', 'noun-person-name', true),
  ('Steve', 'noun-person-name', true),
  ('Superman', 'noun-person-name', true),
  ('Thor', 'noun-person-name', true),
  ('Tyler', 'noun-person-name', true),
  ('Uncle Jerry', 'noun-person-name', true),
  ('Uncle Rico', 'noun-person-name', true),
  ('Wonder Woman', 'noun-person-name', true),
  ('Woody', 'noun-person-name', true),
  ('Zelda', 'noun-person-name', true);

-- Verbs ending in -ing
insert into public.word_bank (word, type, active) values
  ('adding', 'verb-ending-in-ing', true),
  ('admiring', 'verb-ending-in-ing', true),
  ('baking', 'verb-ending-in-ing', true),
  ('balancing', 'verb-ending-in-ing', true),
  ('barking', 'verb-ending-in-ing', true),
  ('biting', 'verb-ending-in-ing', true),
  ('blinking', 'verb-ending-in-ing', true),
  ('boiling', 'verb-ending-in-ing', true),
  ('bouncing', 'verb-ending-in-ing', true),
  ('breathing', 'verb-ending-in-ing', true),
  ('brushing', 'verb-ending-in-ing', true),
  ('burping', 'verb-ending-in-ing', true),
  ('calculating', 'verb-ending-in-ing', true),
  ('calling', 'verb-ending-in-ing', true),
  ('catching', 'verb-ending-in-ing', true),
  ('cheating', 'verb-ending-in-ing', true),
  ('chewing', 'verb-ending-in-ing', true),
  ('cleaning', 'verb-ending-in-ing', true),
  ('coddling', 'verb-ending-in-ing', true),
  ('cooking', 'verb-ending-in-ing', true),
  ('cracking', 'verb-ending-in-ing', true),
  ('crying', 'verb-ending-in-ing', true),
  ('dancing', 'verb-ending-in-ing', true),
  ('delivering', 'verb-ending-in-ing', true),
  ('digging', 'verb-ending-in-ing', true),
  ('diving', 'verb-ending-in-ing', true),
  ('drawing', 'verb-ending-in-ing', true),
  ('dreaming', 'verb-ending-in-ing', true),
  ('drinking', 'verb-ending-in-ing', true),
  ('eating', 'verb-ending-in-ing', true),
  ('editing', 'verb-ending-in-ing', true),
  ('embarking', 'verb-ending-in-ing', true),
  ('exploding', 'verb-ending-in-ing', true),
  ('fabricating', 'verb-ending-in-ing', true),
  ('failing', 'verb-ending-in-ing', true),
  ('falling', 'verb-ending-in-ing', true),
  ('feeding', 'verb-ending-in-ing', true),
  ('fishing', 'verb-ending-in-ing', true),
  ('floating', 'verb-ending-in-ing', true),
  ('flushing', 'verb-ending-in-ing', true),
  ('flying', 'verb-ending-in-ing', true),
  ('forgiving', 'verb-ending-in-ing', true),
  ('galloping', 'verb-ending-in-ing', true),
  ('gathering', 'verb-ending-in-ing', true),
  ('giggling', 'verb-ending-in-ing', true),
  ('giving', 'verb-ending-in-ing', true),
  ('grinding', 'verb-ending-in-ing', true),
  ('growing', 'verb-ending-in-ing', true),
  ('guarding', 'verb-ending-in-ing', true),
  ('jogging', 'verb-ending-in-ing', true),
  ('joining', 'verb-ending-in-ing', true),
  ('joking', 'verb-ending-in-ing', true),
  ('jousting', 'verb-ending-in-ing', true),
  ('juggling', 'verb-ending-in-ing', true),
  ('jumping', 'verb-ending-in-ing', true),
  ('kicking', 'verb-ending-in-ing', true),
  ('kissing', 'verb-ending-in-ing', true),
  ('knitting', 'verb-ending-in-ing', true),
  ('knocking', 'verb-ending-in-ing', true),
  ('lamenting', 'verb-ending-in-ing', true),
  ('landing', 'verb-ending-in-ing', true),
  ('laughing', 'verb-ending-in-ing', true),
  ('learning', 'verb-ending-in-ing', true),
  ('lifting', 'verb-ending-in-ing', true),
  ('loving', 'verb-ending-in-ing', true),
  ('maintaining', 'verb-ending-in-ing', true),
  ('melting', 'verb-ending-in-ing', true),
  ('meowing', 'verb-ending-in-ing', true),
  ('mingling', 'verb-ending-in-ing', true),
  ('motivating', 'verb-ending-in-ing', true),
  ('moving', 'verb-ending-in-ing', true),
  ('neglecting', 'verb-ending-in-ing', true),
  ('negotiating', 'verb-ending-in-ing', true),
  ('nibbling', 'verb-ending-in-ing', true),
  ('observing', 'verb-ending-in-ing', true),
  ('offering', 'verb-ending-in-ing', true),
  ('organizing', 'verb-ending-in-ing', true),
  ('packing', 'verb-ending-in-ing', true),
  ('painting', 'verb-ending-in-ing', true),
  ('pampering', 'verb-ending-in-ing', true),
  ('practicing', 'verb-ending-in-ing', true),
  ('preserving', 'verb-ending-in-ing', true),
  ('punching', 'verb-ending-in-ing', true),
  ('purchasing', 'verb-ending-in-ing', true),
  ('quarrelling', 'verb-ending-in-ing', true),
  ('questioning', 'verb-ending-in-ing', true),
  ('quoting', 'verb-ending-in-ing', true),
  ('radiating', 'verb-ending-in-ing', true),
  ('reaching', 'verb-ending-in-ing', true),
  ('reacting', 'verb-ending-in-ing', true),
  ('reading', 'verb-ending-in-ing', true),
  ('rebelling', 'verb-ending-in-ing', true),
  ('recording', 'verb-ending-in-ing', true),
  ('resting', 'verb-ending-in-ing', true),
  ('rolling', 'verb-ending-in-ing', true),
  ('running', 'verb-ending-in-ing', true),
  ('saving', 'verb-ending-in-ing', true),
  ('screaming', 'verb-ending-in-ing', true),
  ('scrubbing', 'verb-ending-in-ing', true),
  ('sharing', 'verb-ending-in-ing', true),
  ('shining', 'verb-ending-in-ing', true),
  ('shopping', 'verb-ending-in-ing', true),
  ('singing', 'verb-ending-in-ing', true),
  ('skateboarding', 'verb-ending-in-ing', true),
  ('skating', 'verb-ending-in-ing', true),
  ('skipping', 'verb-ending-in-ing', true),
  ('sleeping', 'verb-ending-in-ing', true),
  ('slicing', 'verb-ending-in-ing', true),
  ('sliding', 'verb-ending-in-ing', true),
  ('sneezing', 'verb-ending-in-ing', true),
  ('spinning', 'verb-ending-in-ing', true),
  ('swimming', 'verb-ending-in-ing', true),
  ('talking', 'verb-ending-in-ing', true),
  ('tanning', 'verb-ending-in-ing', true),
  ('teleporting', 'verb-ending-in-ing', true),
  ('throwing', 'verb-ending-in-ing', true),
  ('tickling', 'verb-ending-in-ing', true),
  ('tossing', 'verb-ending-in-ing', true),
  ('traveling', 'verb-ending-in-ing', true),
  ('uncovering', 'verb-ending-in-ing', true),
  ('undermining', 'verb-ending-in-ing', true),
  ('understanding', 'verb-ending-in-ing', true),
  ('upgrading', 'verb-ending-in-ing', true),
  ('vacating', 'verb-ending-in-ing', true),
  ('validating', 'verb-ending-in-ing', true),
  ('verifying', 'verb-ending-in-ing', true),
  ('walking', 'verb-ending-in-ing', true),
  ('warping', 'verb-ending-in-ing', true),
  ('washing', 'verb-ending-in-ing', true),
  ('watching', 'verb-ending-in-ing', true),
  ('waving', 'verb-ending-in-ing', true),
  ('wiggling', 'verb-ending-in-ing', true),
  ('wiping', 'verb-ending-in-ing', true),
  ('wobbling', 'verb-ending-in-ing', true),
  ('working', 'verb-ending-in-ing', true),
  ('writing', 'verb-ending-in-ing', true),
  ('yanking', 'verb-ending-in-ing', true),
  ('yawning', 'verb-ending-in-ing', true),
  ('yelling', 'verb-ending-in-ing', true),
  ('zipping', 'verb-ending-in-ing', true);

-- Plural nouns
insert into public.word_bank (word, type, active) values
  ('acorns', 'noun-plural', true),
  ('adventures', 'noun-plural', true),
  ('airplanes', 'noun-plural', true),
  ('aliens', 'noun-plural', true),
  ('animals', 'noun-plural', true),
  ('astronauts', 'noun-plural', true),
  ('babies', 'noun-plural', true),
  ('bagpipes', 'noun-plural', true),
  ('bags', 'noun-plural', true),
  ('balls', 'noun-plural', true),
  ('baskets', 'noun-plural', true),
  ('bathrooms', 'noun-plural', true),
  ('bears', 'noun-plural', true),
  ('bicycles', 'noun-plural', true),
  ('boats', 'noun-plural', true),
  ('bones', 'noun-plural', true),
  ('books', 'noun-plural', true),
  ('bottles', 'noun-plural', true),
  ('bow ties', 'noun-plural', true),
  ('boxes', 'noun-plural', true),
  ('bricks', 'noun-plural', true),
  ('cameras', 'noun-plural', true),
  ('cars', 'noun-plural', true),
  ('chairs', 'noun-plural', true),
  ('clouds', 'noun-plural', true),
  ('coins', 'noun-plural', true),
  ('computers', 'noun-plural', true),
  ('containers', 'noun-plural', true),
  ('desks', 'noun-plural', true),
  ('diapers', 'noun-plural', true),
  ('dinosaurs', 'noun-plural', true),
  ('doctors', 'noun-plural', true),
  ('doors', 'noun-plural', true),
  ('dreams', 'noun-plural', true),
  ('drums', 'noun-plural', true),
  ('dumpsters', 'noun-plural', true),
  ('earthquakes', 'noun-plural', true),
  ('eggs', 'noun-plural', true),
  ('flowers', 'noun-plural', true),
  ('games', 'noun-plural', true),
  ('gardens', 'noun-plural', true),
  ('gauntlets', 'noun-plural', true),
  ('gifts', 'noun-plural', true),
  ('guitars', 'noun-plural', true),
  ('hats', 'noun-plural', true),
  ('helmets', 'noun-plural', true),
  ('houses', 'noun-plural', true),
  ('ice cubes', 'noun-plural', true),
  ('insects', 'noun-plural', true),
  ('islands', 'noun-plural', true),
  ('kayaks', 'noun-plural', true),
  ('kazoos', 'noun-plural', true),
  ('keyboards', 'noun-plural', true),
  ('keys', 'noun-plural', true),
  ('kittens', 'noun-plural', true),
  ('lakes', 'noun-plural', true),
  ('lamps', 'noun-plural', true),
  ('lights', 'noun-plural', true),
  ('magic beans', 'noun-plural', true),
  ('magnets', 'noun-plural', true),
  ('mailboxes', 'noun-plural', true),
  ('meals', 'noun-plural', true),
  ('motorcycles', 'noun-plural', true),
  ('movies', 'noun-plural', true),
  ('museums', 'noun-plural', true),
  ('napkins', 'noun-plural', true),
  ('ninjas', 'noun-plural', true),
  ('notes', 'noun-plural', true),
  ('occupants', 'noun-plural', true),
  ('oceans', 'noun-plural', true),
  ('octopuses', 'noun-plural', true),
  ('offices', 'noun-plural', true),
  ('packages', 'noun-plural', true),
  ('paintings', 'noun-plural', true),
  ('pencils', 'noun-plural', true),
  ('penguins', 'noun-plural', true),
  ('pictures', 'noun-plural', true),
  ('plates', 'noun-plural', true),
  ('platters', 'noun-plural', true),
  ('puddles', 'noun-plural', true),
  ('race cars', 'noun-plural', true),
  ('raindrops', 'noun-plural', true),
  ('receipts', 'noun-plural', true),
  ('recipes', 'noun-plural', true),
  ('robots', 'noun-plural', true),
  ('rockets', 'noun-plural', true),
  ('saddles', 'noun-plural', true),
  ('sand castles', 'noun-plural', true),
  ('sandwiches', 'noun-plural', true),
  ('shelves', 'noun-plural', true),
  ('shirts', 'noun-plural', true),
  ('shoes', 'noun-plural', true),
  ('socks', 'noun-plural', true),
  ('spaceships', 'noun-plural', true),
  ('spoons', 'noun-plural', true),
  ('stamps', 'noun-plural', true),
  ('stones', 'noun-plural', true),
  ('synthesizers', 'noun-plural', true),
  ('tables', 'noun-plural', true),
  ('teachers', 'noun-plural', true),
  ('televisions', 'noun-plural', true),
  ('tentacles', 'noun-plural', true),
  ('tickets', 'noun-plural', true),
  ('tools', 'noun-plural', true),
  ('trains', 'noun-plural', true),
  ('trash bags', 'noun-plural', true),
  ('trucks', 'noun-plural', true),
  ('unicorns', 'noun-plural', true),
  ('uniforms', 'noun-plural', true),
  ('vampires', 'noun-plural', true),
  ('vehicles', 'noun-plural', true),
  ('video games', 'noun-plural', true),
  ('villagers', 'noun-plural', true),
  ('violins', 'noun-plural', true),
  ('voices', 'noun-plural', true),
  ('wagons', 'noun-plural', true),
  ('wallets', 'noun-plural', true),
  ('warriors', 'noun-plural', true),
  ('windows', 'noun-plural', true),
  ('wires', 'noun-plural', true),
  ('wizards', 'noun-plural', true),
  ('yachts', 'noun-plural', true),
  ('zombies', 'noun-plural', true);

-- Past tense verbs
insert into public.word_bank (word, type, active) values
  ('abandoned', 'verb-past-tense', true),
  ('added', 'verb-past-tense', true),
  ('argued', 'verb-past-tense', true),
  ('ate', 'verb-past-tense', true),
  ('attacked', 'verb-past-tense', true),
  ('baked', 'verb-past-tense', true),
  ('begged', 'verb-past-tense', true),
  ('bit', 'verb-past-tense', true),
  ('bought', 'verb-past-tense', true),
  ('bounced', 'verb-past-tense', true),
  ('built', 'verb-past-tense', true),
  ('burped', 'verb-past-tense', true),
  ('caught', 'verb-past-tense', true),
  ('chased', 'verb-past-tense', true),
  ('chewed', 'verb-past-tense', true),
  ('clapped', 'verb-past-tense', true),
  ('cooked', 'verb-past-tense', true),
  ('counted', 'verb-past-tense', true),
  ('cried', 'verb-past-tense', true),
  ('danced', 'verb-past-tense', true),
  ('dug', 'verb-past-tense', true),
  ('exploded', 'verb-past-tense', true),
  ('fell', 'verb-past-tense', true),
  ('flew', 'verb-past-tense', true),
  ('floated', 'verb-past-tense', true),
  ('forgot', 'verb-past-tense', true),
  ('froze', 'verb-past-tense', true),
  ('giggled', 'verb-past-tense', true),
  ('helped', 'verb-past-tense', true),
  ('jogged', 'verb-past-tense', true),
  ('joked', 'verb-past-tense', true),
  ('jumped', 'verb-past-tense', true),
  ('kicked', 'verb-past-tense', true),
  ('kissed', 'verb-past-tense', true),
  ('laughed', 'verb-past-tense', true),
  ('leaped', 'verb-past-tense', true),
  ('loved', 'verb-past-tense', true),
  ('melted', 'verb-past-tense', true),
  ('morphed', 'verb-past-tense', true),
  ('napped', 'verb-past-tense', true),
  ('played', 'verb-past-tense', true),
  ('pulled', 'verb-past-tense', true),
  ('punched', 'verb-past-tense', true),
  ('purchased', 'verb-past-tense', true),
  ('raced', 'verb-past-tense', true),
  ('ran', 'verb-past-tense', true),
  ('removed', 'verb-past-tense', true),
  ('rolled', 'verb-past-tense', true),
  ('sank', 'verb-past-tense', true),
  ('scared', 'verb-past-tense', true),
  ('screamed', 'verb-past-tense', true),
  ('sliced', 'verb-past-tense', true),
  ('slid', 'verb-past-tense', true),
  ('sneezed', 'verb-past-tense', true),
  ('sold', 'verb-past-tense', true),
  ('spun', 'verb-past-tense', true),
  ('squished', 'verb-past-tense', true),
  ('started', 'verb-past-tense', true),
  ('stole', 'verb-past-tense', true),
  ('stopped', 'verb-past-tense', true),
  ('studied', 'verb-past-tense', true),
  ('swam', 'verb-past-tense', true),
  ('teleported', 'verb-past-tense', true),
  ('thanked', 'verb-past-tense', true),
  ('tickled', 'verb-past-tense', true),
  ('tripped', 'verb-past-tense', true),
  ('typed', 'verb-past-tense', true),
  ('updated', 'verb-past-tense', true),
  ('used', 'verb-past-tense', true),
  ('visited', 'verb-past-tense', true),
  ('waited', 'verb-past-tense', true),
  ('walked', 'verb-past-tense', true),
  ('warned', 'verb-past-tense', true),
  ('wiggled', 'verb-past-tense', true),
  ('wobbled', 'verb-past-tense', true),
  ('worried', 'verb-past-tense', true),
  ('yelled', 'verb-past-tense', true),
  ('zoomed', 'verb-past-tense', true);

-- Body parts
insert into public.word_bank (word, type, active) values
  ('abdomen', 'body-part', true),
  ('ankle', 'body-part', true),
  ('armpit', 'body-part', true),
  ('belly button', 'body-part', true),
  ('bicep', 'body-part', true),
  ('chest', 'body-part', true),
  ('chin', 'body-part', true),
  ('ear', 'body-part', true),
  ('elbow', 'body-part', true),
  ('eye', 'body-part', true),
  ('eyebrow', 'body-part', true),
  ('eyelash', 'body-part', true),
  ('feet', 'body-part', true),
  ('finger', 'body-part', true),
  ('forearm', 'body-part', true),
  ('forehead', 'body-part', true),
  ('hip', 'body-part', true),
  ('jaw', 'body-part', true),
  ('knee cap', 'body-part', true),
  ('knee', 'body-part', true),
  ('left leg', 'body-part', true),
  ('neck', 'body-part', true),
  ('nose', 'body-part', true),
  ('nostril', 'body-part', true),
  ('pinky finger', 'body-part', true),
  ('right leg', 'body-part', true),
  ('ring finger', 'body-part', true),
  ('shoulder', 'body-part', true),
  ('teeth', 'body-part', true),
  ('thumb', 'body-part', true),
  ('toe', 'body-part', true),
  ('tongue', 'body-part', true),
  ('wrist', 'body-part', true);

-- Numbers
insert into public.word_bank (word, type, active) values
  ('1,000', 'number', true),
  ('10', 'number', true),
  ('10,000', 'number', true),
  ('100', 'number', true),
  ('101', 'number', true),
  ('1031', 'number', true),
  ('12', 'number', true),
  ('13', 'number', true),
  ('1337', 'number', true),
  ('14', 'number', true),
  ('15', 'number', true),
  ('16', 'number', true),
  ('17', 'number', true),
  ('18', 'number', true),
  ('19', 'number', true),
  ('2', 'number', true),
  ('20', 'number', true),
  ('21', 'number', true),
  ('22', 'number', true),
  ('23', 'number', true),
  ('24', 'number', true),
  ('25', 'number', true),
  ('26', 'number', true),
  ('27', 'number', true),
  ('28', 'number', true),
  ('29', 'number', true),
  ('3', 'number', true),
  ('3.14', 'number', true),
  ('30', 'number', true),
  ('31', 'number', true),
  ('32', 'number', true),
  ('33', 'number', true),
  ('34', 'number', true),
  ('35', 'number', true),
  ('365', 'number', true),
  ('4', 'number', true),
  ('40', 'number', true),
  ('404', 'number', true),
  ('41', 'number', true),
  ('42', 'number', true),
  ('43', 'number', true),
  ('44', 'number', true),
  ('45', 'number', true),
  ('46', 'number', true),
  ('47', 'number', true),
  ('48', 'number', true),
  ('49', 'number', true),
  ('5', 'number', true),
  ('50', 'number', true),
  ('500', 'number', true),
  ('51', 'number', true),
  ('52', 'number', true),
  ('53', 'number', true),
  ('54', 'number', true),
  ('555', 'number', true),
  ('6', 'number', true),
  ('60', 'number', true),
  ('61', 'number', true),
  ('62', 'number', true),
  ('63', 'number', true),
  ('64', 'number', true),
  ('65', 'number', true),
  ('68', 'number', true),
  ('7', 'number', true),
  ('70', 'number', true),
  ('71', 'number', true),
  ('72', 'number', true),
  ('73', 'number', true),
  ('74', 'number', true),
  ('75', 'number', true),
  ('76', 'number', true),
  ('77', 'number', true),
  ('777', 'number', true),
  ('8', 'number', true),
  ('80', 'number', true),
  ('81', 'number', true),
  ('82', 'number', true),
  ('83', 'number', true),
  ('9', 'number', true),
  ('90', 'number', true),
  ('91', 'number', true),
  ('99', 'number', true);

-- Colors
insert into public.word_bank (word, type, active) values
  ('amber', 'color', true),
  ('amethyst', 'color', true),
  ('aquamarine', 'color', true),
  ('black', 'color', true),
  ('blue', 'color', true),
  ('bright red', 'color', true),
  ('bronze', 'color', true),
  ('brown', 'color', true),
  ('burgundy', 'color', true),
  ('chartreuse', 'color', true),
  ('chrome', 'color', true),
  ('coral', 'color', true),
  ('cornflower blue', 'color', true),
  ('crimson', 'color', true),
  ('cyan', 'color', true),
  ('dark gray', 'color', true),
  ('dark orange', 'color', true),
  ('dark purple', 'color', true),
  ('eggshell', 'color', true),
  ('electric blue', 'color', true),
  ('emerald', 'color', true),
  ('forest green', 'color', true),
  ('goldenrod', 'color', true),
  ('green', 'color', true),
  ('hot pink', 'color', true),
  ('hunter green', 'color', true),
  ('indigo', 'color', true),
  ('kelly green', 'color', true),
  ('lavender', 'color', true),
  ('lemon yellow', 'color', true),
  ('light blue', 'color', true),
  ('light gray', 'color', true),
  ('lime green', 'color', true),
  ('magenta', 'color', true),
  ('maize', 'color', true),
  ('marigold', 'color', true),
  ('mauve', 'color', true),
  ('midnight blue', 'color', true),
  ('mint green', 'color', true),
  ('neon blue', 'color', true),
  ('neon green', 'color', true),
  ('neon pink', 'color', true),
  ('olive green', 'color', true),
  ('orange', 'color', true),
  ('persimmon', 'color', true),
  ('pink', 'color', true),
  ('pumpkin orange', 'color', true),
  ('purple', 'color', true),
  ('rainbow', 'color', true),
  ('red', 'color', true),
  ('royal blue', 'color', true),
  ('saffron', 'color', true),
  ('sapphire blue', 'color', true),
  ('school bus yellow', 'color', true),
  ('silver', 'color', true),
  ('sparkly gold', 'color', true),
  ('steel blue', 'color', true),
  ('taupe', 'color', true),
  ('turquoise', 'color', true),
  ('tuscan red', 'color', true),
  ('violet', 'color', true),
  ('white', 'color', true),
  ('yellow', 'color', true);

-- Animals
insert into public.word_bank (word, type, active) values
  ('aardvark', 'animal', true),
  ('alligator', 'animal', true),
  ('alpaca', 'animal', true),
  ('anteater', 'animal', true),
  ('armadillo', 'animal', true),
  ('axolotl', 'animal', true),
  ('baboon', 'animal', true),
  ('badger', 'animal', true),
  ('bald eagle', 'animal', true),
  ('bat', 'animal', true),
  ('beaver', 'animal', true),
  ('beetle', 'animal', true),
  ('bison', 'animal', true),
  ('blue whale', 'animal', true),
  ('bobcat', 'animal', true),
  ('brown bear', 'animal', true),
  ('butterfly', 'animal', true),
  ('camel', 'animal', true),
  ('capybara', 'animal', true),
  ('centipede', 'animal', true),
  ('chameleon', 'animal', true),
  ('cheetah', 'animal', true),
  ('chicken', 'animal', true),
  ('chimpanzee', 'animal', true),
  ('chupacabra', 'animal', true),
  ('clownfish', 'animal', true),
  ('cow', 'animal', true),
  ('coyote', 'animal', true),
  ('crocodile', 'animal', true),
  ('deer', 'animal', true),
  ('dog', 'animal', true),
  ('dolphin', 'animal', true),
  ('donkey', 'animal', true),
  ('dragon', 'noun', true),
  ('eagle', 'animal', true),
  ('earthworm', 'animal', true),
  ('eel', 'animal', true),
  ('elephant', 'animal', true),
  ('farret', 'animal', true),
  ('flamingo', 'animal', true),
  ('fox', 'animal', true),
  ('frog', 'animal', true),
  ('fruit fly', 'animal', true),
  ('giraffe', 'animal', true),
  ('goat', 'animal', true),
  ('gorilla', 'animal', true),
  ('great white shark', 'animal', true),
  ('grizzly bear', 'animal', true),
  ('hammerhead shark', 'animal', true),
  ('hamster', 'animal', true),
  ('hedgehog', 'animal', true),
  ('hermit crab', 'animal', true),
  ('hippopotamus', 'animal', true),
  ('horse', 'animal', true),
  ('house cat', 'animal', true),
  ('hyena', 'animal', true),
  ('iguana', 'animal', true),
  ('jellyfish', 'animal', true),
  ('kangaroo', 'animal', true),
  ('kitten', 'animal', true),
  ('koala', 'animal', true),
  ('komodo dragon', 'animal', true),
  ('leopard', 'animal', true),
  ('lion', 'animal', true),
  ('lizard', 'animal', true),
  ('llama', 'animal', true),
  ('lobster', 'animal', true),
  ('mallard', 'animal', true),
  ('meerkat', 'animal', true),
  ('mongoose', 'animal', true),
  ('narwhal', 'animal', true),
  ('newt', 'animal', true),
  ('ocelot', 'animal', true),
  ('octopus', 'animal', true),
  ('ostrich', 'animal', true),
  ('otter', 'animal', true),
  ('owl', 'animal', true),
  ('ox', 'animal', true),
  ('panda', 'animal', true),
  ('pangolin', 'animal', true),
  ('parrot', 'animal', true),
  ('peacock', 'animal', true),
  ('pelican', 'animal', true),
  ('penguin', 'animal', true),
  ('pig', 'animal', true),
  ('pigeon', 'animal', true),
  ('platypus', 'animal', true),
  ('polar bear', 'animal', true),
  ('porcupine', 'animal', true),
  ('quokka', 'animal', true),
  ('rabbit', 'animal', true),
  ('racoon', 'animal', true),
  ('rainbow trout', 'animal', true),
  ('rattlesnake', 'animal', true),
  ('red panda', 'animal', true),
  ('reindeer', 'animal', true),
  ('roadrunner', 'animal', true),
  ('sasquatch', 'animal', true),
  ('scorpion', 'animal', true),
  ('sea lion', 'animal', true),
  ('seahorse', 'animal', true),
  ('skunk', 'animal', true),
  ('sloth', 'animal', true),
  ('squirrel', 'animal', true),
  ('tasmanian devil', 'animal', true),
  ('toad', 'animal', true),
  ('tortoise', 'animal', true),
  ('toucan', 'animal', true),
  ('vulture', 'animal', true),
  ('walrus', 'animal', true),
  ('werewolf', 'animal', true),
  ('wolverine', 'animal', true),
  ('woodpecker', 'animal', true),
  ('yak', 'animal', true),
  ('zebra', 'animal', true);

-- Food
insert into public.word_bank (word, type, active) values
  ('apple pie', 'food', true),
  ('avocado', 'food', true),
  ('bacon', 'food', true),
  ('baked beans', 'food', true),
  ('banana', 'food', true),
  ('beef stew', 'food', true),
  ('bread', 'food', true),
  ('broccoli', 'food', true),
  ('brown rice', 'food', true),
  ('burrito', 'food', true),
  ('candy bar', 'food', true),
  ('cheddar cheese', 'food', true),
  ('cheese quesadilla', 'food', true),
  ('cherry pie', 'food', true),
  ('chicken noodle soup', 'food', true),
  ('chicken nuggets', 'food', true),
  ('chocolate cake', 'food', true),
  ('chocolate ice cream', 'food', true),
  ('chocolate pudding', 'food', true),
  ('cookies', 'food', true),
  ('cupcake', 'food', true),
  ('donuts', 'food', true),
  ('enchiladas', 'food', true),
  ('flour tortilla', 'food', true),
  ('french fries', 'food', true),
  ('fried chicken', 'food', true),
  ('green peas', 'food', true),
  ('hamburger', 'food', true),
  ('horseradish', 'food', true),
  ('hot dog', 'food', true),
  ('ice cream', 'food', true),
  ('mac and cheese', 'food', true),
  ('nachos', 'food', true),
  ('orange juice', 'food', true),
  ('pancakes', 'food', true),
  ('papaya', 'food', true),
  ('pasta', 'food', true),
  ('peanut butter', 'food', true),
  ('pickles', 'food', true),
  ('pizza', 'food', true),
  ('popcorn', 'food', true),
  ('popsicle', 'food', true),
  ('ramen', 'food', true),
  ('sandwich', 'food', true),
  ('sausage', 'food', true),
  ('scrambled eggs', 'food', true),
  ('spaghetti', 'food', true),
  ('steak', 'food', true),
  ('sushi', 'food', true),
  ('tacos', 'food', true),
  ('tuna fish', 'food', true),
  ('waffles', 'food', true),
  ('white rice', 'food', true);

-- Exclamations
insert into public.word_bank (word, type, active) values
  ('Are you sure about that?', 'exclamation', true),
  ('Bam', 'exclamation', true),
  ('Blimey', 'exclamation', true),
  ('Crikey', 'exclamation', true),
  ('Dang', 'exclamation', true),
  ('Egads', 'exclamation', true),
  ('Gadzooks', 'exclamation', true),
  ('Golly', 'exclamation', true),
  ('Holy cow', 'exclamation', true),
  ('Holy moly', 'exclamation', true),
  ('Jeepers', 'exclamation', true),
  ('LOL', 'exclamation', true),
  ('OMG', 'exclamation', true),
  ('Oh no', 'exclamation', true),
  ('Ouch', 'exclamation', true),
  ('Sheesh', 'exclamation', true),
  ('Thats crazy', 'exclamation', true),
  ('Uh-oh', 'exclamation', true),
  ('What the heck?', 'exclamation', true),
  ('Whoa', 'exclamation', true),
  ('Whoops', 'exclamation', true),
  ('Wow', 'exclamation', true),
  ('Yay', 'exclamation', true),
  ('Yikes', 'exclamation', true),
  ('Yowch', 'exclamation', true),
  ('Yowza', 'exclamation', true),
  ('Zoinks', 'exclamation', true);

-- Place names
insert into public.word_bank (word, type, active) values
  ('Alabama', 'noun-place-name', true),
  ('Alaska', 'noun-place-name', true),
  ('Antarctica', 'noun-place-name', true),
  ('Arizona', 'noun-place-name', true),
  ('Asgard', 'noun-place-name', true),
  ('Atlantis', 'noun-place-name', true),
  ('Berlin', 'noun-place-name', true),
  ('Bolivia', 'noun-place-name', true),
  ('Brooklyn', 'noun-place-name', true),
  ('Canada', 'noun-place-name', true),
  ('Chicago', 'noun-place-name', true),
  ('Cleveland', 'noun-place-name', true),
  ('Colorado', 'noun-place-name', true),
  ('Costa Rica', 'noun-place-name', true),
  ('Dallas', 'noun-place-name', true),
  ('Detroit', 'noun-place-name', true),
  ('Disneyland', 'noun-place-name', true),
  ('Eiffel Tower', 'noun-place-name', true),
  ('Florida', 'noun-place-name', true),
  ('Gotham City', 'noun-place-name', true),
  ('Hawaii', 'noun-place-name', true),
  ('Hogwarts', 'noun-place-name', true),
  ('Jupiter', 'noun-place-name', true),
  ('Las Vegas', 'noun-place-name', true),
  ('London', 'noun-place-name', true),
  ('Los Angeles', 'noun-place-name', true),
  ('Mars', 'noun-place-name', true),
  ('Mexico', 'noun-place-name', true),
  ('Miami', 'noun-place-name', true),
  ('Michigan', 'noun-place-name', true),
  ('Mordor', 'noun-place-name', true),
  ('Mount Everest', 'noun-place-name', true),
  ('Narnia', 'noun-place-name', true),
  ('Nebraska', 'noun-place-name', true),
  ('New Jersey', 'noun-place-name', true),
  ('New Mexico', 'noun-place-name', true),
  ('New York', 'noun-place-name', true),
  ('New Zealand', 'noun-place-name', true),
  ('Paris', 'noun-place-name', true),
  ('Phoenix', 'noun-place-name', true),
  ('Pluto', 'noun-place-name', true),
  ('Portland', 'noun-place-name', true),
  ('San Diego', 'noun-place-name', true),
  ('San Francisco', 'noun-place-name', true),
  ('Saturn', 'noun-place-name', true),
  ('Seattle', 'noun-place-name', true),
  ('Singapore', 'noun-place-name', true),
  ('Springfield', 'noun-place-name', true),
  ('Stockholm', 'noun-place-name', true),
  ('Texas', 'noun-place-name', true),
  ('The Moon', 'noun-place-name', true),
  ('The North Pole', 'noun-place-name', true),
  ('The Pacific Ocean', 'noun-place-name', true),
  ('The Shire', 'noun-place-name', true),
  ('Tokyo', 'noun-place-name', true),
  ('Toronto', 'noun-place-name', true),
  ('Valhalla', 'noun-place-name', true),
  ('Vancouver', 'noun-place-name', true),
  ('Wakanda', 'noun-place-name', true),
  ('Walmart', 'noun-place-name', true),
  ('Wonderland', 'noun-place-name', true);

-- Seed a few story templates
insert into public.story_templates (title, template, category, active) values
  (
    'The Great Adventure',
    '{
      "story": "Once upon a time, {0} the {1} explorer discovered a {2} {3} in {4}. Inside was a {5} {6} that could {7} when touched! A wild {8} appeared and started {9}, so {0} had to {10} away really {11}.",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "color"},
        {"position": 3, "type": "noun"},
        {"position": 4, "type": "noun-place-name"},
        {"position": 5, "type": "adjective"},
        {"position": 6, "type": "animal"},
        {"position": 7, "type": "verb"},
        {"position": 8, "type": "animal"},
        {"position": 9, "type": "verb-ending-in-ing"},
        {"position": 10, "type": "verb"},
        {"position": 11, "type": "adverb"}
      ]
    }',
    'adventure',
    true
  ),
  (
    'A Day at School',
    '{
      "story": "It was a {0} morning when our teacher {1} announced we would {2} today. My friend {3} started {4} loudly! Suddenly, a {5} {6} ran into our classroom and began {7} on the {8}. Everyone was {9} until the principal came in carrying {10} {11}.",
      "placeholders": [
        {"position": 0, "type": "adjective"},
        {"position": 1, "type": "noun-person-name"},
        {"position": 2, "type": "verb"},
        {"position": 3, "type": "noun-person-name"},
        {"position": 4, "type": "verb-ending-in-ing"},
        {"position": 5, "type": "color"},
        {"position": 6, "type": "animal"},
        {"position": 7, "type": "verb-ending-in-ing"},
        {"position": 8, "type": "noun"},
        {"position": 9, "type": "verb-ending-in-ing"},
        {"position": 10, "type": "number"},
        {"position": 11, "type": "noun-plural"}
      ]
    }',
    'school',
    true
  ),
  (
    'The Cooking Disaster',
    '{
      "story": "{0}! I tried to make {1} but accidentally added {2} cups of {3} {4}. My pet {5} was watching and started {6} when the kitchen turned {7}. The smoke alarm went off and everything smelled like {8}! My {9} {10} neighbor came over and said it tasted {11}.",
      "placeholders": [
        {"position": 0, "type": "exclamation"},
        {"position": 1, "type": "food"},
        {"position": 2, "type": "number"},
        {"position": 3, "type": "color"},
        {"position": 4, "type": "food"},
        {"position": 5, "type": "animal"},
        {"position": 6, "type": "verb-ending-in-ing"},
        {"position": 7, "type": "color"},
        {"position": 8, "type": "noun-plural"},
        {"position": 9, "type": "adjective"},
        {"position": 10, "type": "noun-person-name"},
        {"position": 11, "type": "adjective"}
      ]
    }',
    'cooking',
    true
  ),
  (
    'My Weird Pet',
    '{
      "story": "I adopted a {0} {1} named {2} from the shelter. Every morning, {2} wakes me up by {3} on my {4}. For breakfast, {2} only eats {5} covered in {6} {7}. Yesterday, {2} {8} to {9} and brought back {10} {11}. My friends think {2} is {12}, but I love my pet!",
      "placeholders": [
        {"position": 0, "type": "color"},
        {"position": 1, "type": "animal"},
        {"position": 2, "type": "noun-person-name"},
        {"position": 3, "type": "verb-ending-in-ing"},
        {"position": 4, "type": "body-part"},
        {"position": 5, "type": "food"},
        {"position": 6, "type": "adjective"},
        {"position": 7, "type": "food"},
        {"position": 8, "type": "verb-past-tense"},
        {"position": 9, "type": "noun-place-name"},
        {"position": 10, "type": "number"},
        {"position": 11, "type": "noun-plural"},
        {"position": 12, "type": "adjective"}
      ]
    }',
    'pets',
    true
  ),
  (
    'The Family Vacation',
    '{
      "story": "Our family took a {0} vacation to {1}. We packed our {2} {3} and drove for {4} hours. At the hotel, my sibling {5} brought their pet {6} who kept {7} in the lobby. The restaurant only served {8} {9} that tasted like {10}. {11}! It was the most {12} vacation ever!",
      "placeholders": [
        {"position": 0, "type": "adjective"},
        {"position": 1, "type": "noun-place-name"},
        {"position": 2, "type": "color"},
        {"position": 3, "type": "noun"},
        {"position": 4, "type": "number"},
        {"position": 5, "type": "noun-person-name"},
        {"position": 6, "type": "animal"},
        {"position": 7, "type": "verb-ending-in-ing"},
        {"position": 8, "type": "adjective"},
        {"position": 9, "type": "food"},
        {"position": 10, "type": "noun-plural"},
        {"position": 11, "type": "exclamation"},
        {"position": 12, "type": "adjective"}
      ]
    }',
    'vacation',
    true
  ),
  (
    'The Science Experiment',
    '{
      "story": "In science class, my partner {0} and I mixed {1} {2} with {3} cups of {4} {5}. The mixture turned {6} and started {7}! A {8} {9} jumped out of the beaker and began {10} around the room. Everyone was {11} until it ate the teacher''s {12}!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "number"},
        {"position": 2, "type": "noun-plural"},
        {"position": 3, "type": "number"},
        {"position": 4, "type": "color"},
        {"position": 5, "type": "food"},
        {"position": 6, "type": "color"},
        {"position": 7, "type": "verb-ending-in-ing"},
        {"position": 8, "type": "adjective"},
        {"position": 9, "type": "animal"},
        {"position": 10, "type": "verb-ending-in-ing"},
        {"position": 11, "type": "verb-ending-in-ing"},
        {"position": 12, "type": "noun"}
      ]
    }',
    'science',
    true
  ),
  (
    'The Job Interview',
    '{
      "story": "I walked {0} into the office for my job interview. The interviewer {1} asked me to describe myself in {2} words. I said I was {3}, {4}, and really good at {5}. For my skill demonstration, I had to {6} while balancing a {7} on my {8}. They said I was the most {9} candidate ever and hired me to work with {10} {11}!",
      "placeholders": [
        {"position": 0, "type": "adverb"},
        {"position": 1, "type": "noun-person-name"},
        {"position": 2, "type": "number"},
        {"position": 3, "type": "adjective"},
        {"position": 4, "type": "adjective"},
        {"position": 5, "type": "verb-ending-in-ing"},
        {"position": 6, "type": "verb"},
        {"position": 7, "type": "animal"},
        {"position": 8, "type": "body-part"},
        {"position": 9, "type": "adjective"},
        {"position": 10, "type": "adjective"},
        {"position": 11, "type": "noun-plural"}
      ]
    }',
    'work',
    true
  ),
  (
    'The Birthday Party',
    '{
      "story": "It was {0}''s {1}th birthday party! We decorated with {2} balloons and the cake was shaped like a giant {3}. For entertainment, we hired a {4} {5} to {6} for everyone. When {0} opened their present, a {7} {8} jumped out and started {9}! The whole party was {10} and we all {11} until midnight!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "number"},
        {"position": 2, "type": "color"},
        {"position": 3, "type": "animal"},
        {"position": 4, "type": "adjective"},
        {"position": 5, "type": "noun"},
        {"position": 6, "type": "verb"},
        {"position": 7, "type": "color"},
        {"position": 8, "type": "animal"},
        {"position": 9, "type": "verb-ending-in-ing"},
        {"position": 10, "type": "adjective"},
        {"position": 11, "type": "verb-past-tense"}
      ]
    }',
    'party',
    true
  ),
  (
    'The Superhero Origin Story',
    '{
      "story": "My name is {0}, and this is how I became a superhero! A {1} {2} bit me on my {3} and I felt {4}. I discovered I could {5} {6} and shoot {7} {8} from my {9}. I made a costume and called myself Captain {10}. Now I protect {11} from danger!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "color"},
        {"position": 2, "type": "animal"},
        {"position": 3, "type": "body-part"},
        {"position": 4, "type": "adjective"},
        {"position": 5, "type": "verb"},
        {"position": 6, "type": "adverb"},
        {"position": 7, "type": "adjective"},
        {"position": 8, "type": "noun-plural"},
        {"position": 9, "type": "body-part"},
        {"position": 10, "type": "noun"},
        {"position": 11, "type": "noun-place-name"}
      ]
    }',
    'superhero',
    true
  ),
  (
    'The Lost Treasure',
    '{
      "story": "My friend {0} and I searched for treasure in {1}. We brought {2} {3} and my pet {4}. After {5} hours, we found a {6} door and discovered {7} {8} inside! There was a note from {9} saying ''{10}! You found my secret {11} collection!''",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "noun-place-name"},
        {"position": 2, "type": "number"},
        {"position": 3, "type": "noun-plural"},
        {"position": 4, "type": "animal"},
        {"position": 5, "type": "number"},
        {"position": 6, "type": "color"},
        {"position": 7, "type": "number"},
        {"position": 8, "type": "noun-plural"},
        {"position": 9, "type": "noun-person-name"},
        {"position": 10, "type": "exclamation"},
        {"position": 11, "type": "noun"}
      ]
    }',
    'adventure',
    true
  ),
  (
    'The Camping Trip',
    '{
      "story": "Our scout troop went camping near {0}. We hiked {1} miles and set up {2} tents. That night, a wild {3} appeared and started {4} our {5}! Counselor {6} tried to {7} it away, but instead it {8} and joined us around the fire. We fed it {9} and it became our new {10} friend!",
      "placeholders": [
        {"position": 0, "type": "noun-place-name"},
        {"position": 1, "type": "number"},
        {"position": 2, "type": "color"},
        {"position": 3, "type": "animal"},
        {"position": 4, "type": "verb-ending-in-ing"},
        {"position": 5, "type": "noun-plural"},
        {"position": 6, "type": "noun-person-name"},
        {"position": 7, "type": "verb"},
        {"position": 8, "type": "verb-past-tense"},
        {"position": 9, "type": "food"},
        {"position": 10, "type": "adjective"}
      ]
    }',
    'adventure',
    true
  ),
  (
    'The Substitute Teacher',
    '{
      "story": "Our substitute teacher {0} walked in wearing a {1} {2} and carrying {3} {4}. They taught us to {5} using only our {6}. During recess, {0} {7} and broke the {8} {9}. In math class, they made us count {10}. Turns out {0} wasn''t even a real teacher, just a {11} {12} who wandered in!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "color"},
        {"position": 2, "type": "noun"},
        {"position": 3, "type": "number"},
        {"position": 4, "type": "noun-plural"},
        {"position": 5, "type": "verb"},
        {"position": 6, "type": "body-part"},
        {"position": 7, "type": "verb-past-tense"},
        {"position": 8, "type": "adjective"},
        {"position": 9, "type": "noun"},
        {"position": 10, "type": "noun-plural"},
        {"position": 11, "type": "adjective"},
        {"position": 12, "type": "animal"}
      ]
    }',
    'school',
    true
  ),
  (
    'The Field Trip',
    '{
      "story": "Our class visited the {0} museum in {1}. Our guide {2} showed us {3} exhibits about {4} {5}. My friend {6} accidentally {7} into a {8} statue of a {9}. The alarm went off and {10} security guards came running! We got kicked out and ate lunch on {11} {12} in the parking lot.",
      "placeholders": [
        {"position": 0, "type": "adjective"},
        {"position": 1, "type": "noun-place-name"},
        {"position": 2, "type": "noun-person-name"},
        {"position": 3, "type": "number"},
        {"position": 4, "type": "adjective"},
        {"position": 5, "type": "noun-plural"},
        {"position": 6, "type": "noun-person-name"},
        {"position": 7, "type": "verb-past-tense"},
        {"position": 8, "type": "color"},
        {"position": 9, "type": "animal"},
        {"position": 10, "type": "number"},
        {"position": 11, "type": "color"},
        {"position": 12, "type": "noun-plural"}
      ]
    }',
    'school',
    true
  ),
  (
    'The Bake Sale Disaster',
    '{
      "story": "I made {0} {1} for the bake sale using {2}''s recipe. I mixed {3} cups of {4} and {5} {6}. When I baked it, everything turned {7} and smelled like {8}! {9} took one bite and started {10}. Nobody bought my {1}, but the {11} {12} next door ate it all!",
      "placeholders": [
        {"position": 0, "type": "number"},
        {"position": 1, "type": "food"},
        {"position": 2, "type": "noun-person-name"},
        {"position": 3, "type": "number"},
        {"position": 4, "type": "food"},
        {"position": 5, "type": "color"},
        {"position": 6, "type": "food"},
        {"position": 7, "type": "color"},
        {"position": 8, "type": "noun-plural"},
        {"position": 9, "type": "noun-person-name"},
        {"position": 10, "type": "verb-ending-in-ing"},
        {"position": 11, "type": "adjective"},
        {"position": 12, "type": "animal"}
      ]
    }',
    'cooking',
    true
  ),
  (
    'The Food Truck',
    '{
      "story": "My cousin {0} started a food truck that serves {1} {2} topped with {3} {4}. I tried it and my {5} felt {6}! The flavor was so {7} that I started {8}. {0} said the secret ingredient is {9} mixed with {10} {11}. Now there''s a {12} hour wait!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "food"},
        {"position": 3, "type": "color"},
        {"position": 4, "type": "food"},
        {"position": 5, "type": "body-part"},
        {"position": 6, "type": "adjective"},
        {"position": 7, "type": "adjective"},
        {"position": 8, "type": "verb-ending-in-ing"},
        {"position": 9, "type": "noun-plural"},
        {"position": 10, "type": "color"},
        {"position": 11, "type": "food"},
        {"position": 12, "type": "number"}
      ]
    }',
    'cooking',
    true
  ),
  (
    'The Talent Show',
    '{
      "story": "I signed up for the talent show to {0} while {1} and playing the {2} with my {3}. I practiced for {4} days. On show night, I wore my {5} {6} and everything was going {7} until a {8} {9} ran on stage and started {10}! Judge {11} gave me a {12} and said ''{13}!''",
      "placeholders": [
        {"position": 0, "type": "verb"},
        {"position": 1, "type": "verb-ending-in-ing"},
        {"position": 2, "type": "noun"},
        {"position": 3, "type": "body-part"},
        {"position": 4, "type": "number"},
        {"position": 5, "type": "color"},
        {"position": 6, "type": "noun"},
        {"position": 7, "type": "adverb"},
        {"position": 8, "type": "adjective"},
        {"position": 9, "type": "animal"},
        {"position": 10, "type": "verb-ending-in-ing"},
        {"position": 11, "type": "noun-person-name"},
        {"position": 12, "type": "number"},
        {"position": 13, "type": "exclamation"}
      ]
    }',
    'party',
    true
  ),
  (
    'The Wedding',
    '{
      "story": "I went to {0}''s wedding in {1}. The ceremony was in a {2} {3} decorated with {4} flowers. During the vows, someone''s pet {5} started {6} loudly! At the reception, we ate {7} {8} and the DJ {9} played {10} music. The cake was shaped like a giant {11} and when they cut it, {12} {13} fell out!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "noun-place-name"},
        {"position": 2, "type": "adjective"},
        {"position": 3, "type": "noun"},
        {"position": 4, "type": "color"},
        {"position": 5, "type": "animal"},
        {"position": 6, "type": "verb-ending-in-ing"},
        {"position": 7, "type": "adjective"},
        {"position": 8, "type": "food"},
        {"position": 9, "type": "noun-person-name"},
        {"position": 10, "type": "adjective"},
        {"position": 11, "type": "animal"},
        {"position": 12, "type": "number"},
        {"position": 13, "type": "noun-plural"}
      ]
    }',
    'party',
    true
  ),
  (
    'The Zoo Trip',
    '{
      "story": "My family went to the zoo in {0} and it was {1}! We saw {2} {3} who were {4}. The zookeeper {5} said they eat {6} {7} for every meal. At the petting zoo, I got to pet a baby {8} that smelled like {9}. Dad {10} and dropped his {11} in the {12} habitat!",
      "placeholders": [
        {"position": 0, "type": "noun-place-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "color"},
        {"position": 3, "type": "animal"},
        {"position": 4, "type": "verb-ending-in-ing"},
        {"position": 5, "type": "noun-person-name"},
        {"position": 6, "type": "number"},
        {"position": 7, "type": "food"},
        {"position": 8, "type": "animal"},
        {"position": 9, "type": "noun-plural"},
        {"position": 10, "type": "verb-past-tense"},
        {"position": 11, "type": "noun"},
        {"position": 12, "type": "adjective"}
      ]
    }',
    'pets',
    true
  ),
  (
    'The Veterinarian Visit',
    '{
      "story": "I took my pet {0} to the vet because it wouldn''t stop {1}. Dr. {2} examined its {3} and said ''{4}! Your {0} has swallowed {5} {6}!'' After surgery, they pulled out the {6} plus a {7} {8} we didn''t know was missing! The bill was {9} dollars and now my {0} has to wear a {10} cone. At least it''s {11} now!",
      "placeholders": [
        {"position": 0, "type": "animal"},
        {"position": 1, "type": "verb-ending-in-ing"},
        {"position": 2, "type": "noun-person-name"},
        {"position": 3, "type": "body-part"},
        {"position": 4, "type": "exclamation"},
        {"position": 5, "type": "number"},
        {"position": 6, "type": "noun-plural"},
        {"position": 7, "type": "adjective"},
        {"position": 8, "type": "noun"},
        {"position": 9, "type": "number"},
        {"position": 10, "type": "color"},
        {"position": 11, "type": "adjective"}
      ]
    }',
    'pets',
    true
  ),
  (
    'The Beach Day',
    '{
      "story": "We went to the beach near {0} and it was {1} degrees! I wore my {2} {3} and brought {4} {5}. While building a sandcastle, I found {6} {7} buried in the sand. Suddenly, a {8} wave hit and a {9} {10} washed up on shore! My friend {11} tried to {12} it back to the ocean but it just {13} {14}.",
      "placeholders": [
        {"position": 0, "type": "noun-place-name"},
        {"position": 1, "type": "number"},
        {"position": 2, "type": "color"},
        {"position": 3, "type": "noun"},
        {"position": 4, "type": "number"},
        {"position": 5, "type": "noun-plural"},
        {"position": 6, "type": "number"},
        {"position": 7, "type": "noun-plural"},
        {"position": 8, "type": "adjective"},
        {"position": 9, "type": "color"},
        {"position": 10, "type": "animal"},
        {"position": 11, "type": "noun-person-name"},
        {"position": 12, "type": "verb"},
        {"position": 13, "type": "verb-past-tense"},
        {"position": 14, "type": "adverb"}
      ]
    }',
    'vacation',
    true
  ),
  (
    'The Hotel Room',
    '{
      "story": "Our hotel room in {0} was supposed to be {1}, but it was actually {2}! The bed smelled like {3} and when I turned on the {4}, {5} {6} fell out! The bathroom had a {7} {8} living in the shower. Room service brought us {9} instead of the {10} we ordered. The manager offered us {11} dollars off!",
      "placeholders": [
        {"position": 0, "type": "noun-place-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "adjective"},
        {"position": 3, "type": "food"},
        {"position": 4, "type": "noun"},
        {"position": 5, "type": "number"},
        {"position": 6, "type": "noun-plural"},
        {"position": 7, "type": "color"},
        {"position": 8, "type": "animal"},
        {"position": 9, "type": "food"},
        {"position": 10, "type": "food"},
        {"position": 11, "type": "number"}
      ]
    }',
    'vacation',
    true
  ),
  (
    'The Chemistry Lab',
    '{
      "story": "In chemistry class, my partner {0} and I mixed {1} drops of {2} {3} with {4} grams of {5} {6}. Professor {7} warned us to be careful, but {0} added too much! The beaker started {8} and turned {9}. {10} {11} floated everywhere and {12} firefighters showed up!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "number"},
        {"position": 2, "type": "color"},
        {"position": 3, "type": "food"},
        {"position": 4, "type": "number"},
        {"position": 5, "type": "adjective"},
        {"position": 6, "type": "noun-plural"},
        {"position": 7, "type": "noun-person-name"},
        {"position": 8, "type": "verb-ending-in-ing"},
        {"position": 9, "type": "color"},
        {"position": 10, "type": "adjective"},
        {"position": 11, "type": "noun-plural"},
        {"position": 12, "type": "number"}
      ]
    }',
    'science',
    true
  ),
  (
    'The Robot Invention',
    '{
      "story": "For the science fair, I built a robot that could {0} automatically. I used {1} {2} and a {3} {4} for the brain. When I pressed the {5} button, it started {6} and began to {7} {8}! Judge {9} was impressed until the robot went {10} and started destroying everything. The local news called me the ''{11} inventor''!",
      "placeholders": [
        {"position": 0, "type": "verb"},
        {"position": 1, "type": "number"},
        {"position": 2, "type": "noun-plural"},
        {"position": 3, "type": "color"},
        {"position": 4, "type": "food"},
        {"position": 5, "type": "color"},
        {"position": 6, "type": "verb-ending-in-ing"},
        {"position": 7, "type": "verb"},
        {"position": 8, "type": "adverb"},
        {"position": 9, "type": "noun-person-name"},
        {"position": 10, "type": "adjective"},
        {"position": 11, "type": "adjective"}
      ]
    }',
    'science',
    true
  ),
  (
    'The First Day of Work',
    '{
      "story": "I was so {0} for my first day at {1}. My boss {2} showed me the {3} {4} where I would be {5}. My first task was to {6} {7} {8} before lunch. I accidentally {9} the {10} {11} and everything turned {12}. A customer asked for {13} and I panicked and gave them a {14} instead!",
      "placeholders": [
        {"position": 0, "type": "adjective"},
        {"position": 1, "type": "noun"},
        {"position": 2, "type": "noun-person-name"},
        {"position": 3, "type": "adjective"},
        {"position": 4, "type": "noun"},
        {"position": 5, "type": "verb-ending-in-ing"},
        {"position": 6, "type": "verb"},
        {"position": 7, "type": "number"},
        {"position": 8, "type": "noun-plural"},
        {"position": 9, "type": "verb-past-tense"},
        {"position": 10, "type": "color"},
        {"position": 11, "type": "noun"},
        {"position": 12, "type": "color"},
        {"position": 13, "type": "noun-plural"},
        {"position": 14, "type": "animal"}
      ]
    }',
    'work',
    true
  ),
  (
    'The Office Meeting',
    '{
      "story": "We had a {0} meeting today. The CEO {1} walked in carrying {2} {3} and announced we would now be selling {4} {5}. Everyone started {6} at once. My coworker {7} suggested we should {8} to increase sales. Someone''s {9} started {10} and a {11} {12} got into the conference room!",
      "placeholders": [
        {"position": 0, "type": "adjective"},
        {"position": 1, "type": "noun-person-name"},
        {"position": 2, "type": "number"},
        {"position": 3, "type": "noun-plural"},
        {"position": 4, "type": "color"},
        {"position": 5, "type": "noun-plural"},
        {"position": 6, "type": "verb-ending-in-ing"},
        {"position": 7, "type": "noun-person-name"},
        {"position": 8, "type": "verb"},
        {"position": 9, "type": "noun"},
        {"position": 10, "type": "verb-ending-in-ing"},
        {"position": 11, "type": "adjective"},
        {"position": 12, "type": "animal"}
      ]
    }',
    'work',
    true
  ),
  (
    'The Evil Villain',
    '{
      "story": "My superhero nemesis is {0}, the most {1} villain in {2}! They can {3} with their {4} and shoot {5} {6} from their {7}. Their evil lair is hidden inside a {8} {9} filled with {10} {11}. Last night, I defeated them using my secret weapon - a {12} {13}! They escaped yelling ''{14}!''",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "noun-place-name"},
        {"position": 3, "type": "verb"},
        {"position": 4, "type": "body-part"},
        {"position": 5, "type": "color"},
        {"position": 6, "type": "noun-plural"},
        {"position": 7, "type": "body-part"},
        {"position": 8, "type": "adjective"},
        {"position": 9, "type": "noun"},
        {"position": 10, "type": "number"},
        {"position": 11, "type": "animal"},
        {"position": 12, "type": "adjective"},
        {"position": 13, "type": "noun"},
        {"position": 14, "type": "exclamation"}
      ]
    }',
    'superhero',
    true
  ),
  (
    'The Sidekick',
    '{
      "story": "My superhero sidekick is {0}! They may be {1}, but they can {2} really {3}. Their costume is made of {4} {5} with a {6} cape. Last week, we stopped a runaway {7} that was {8} down the street. {0} used their {9} to {10} it before it could crash. The mayor gave us a key to the city made of {11} {12}!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "verb"},
        {"position": 3, "type": "adverb"},
        {"position": 4, "type": "color"},
        {"position": 5, "type": "noun-plural"},
        {"position": 6, "type": "adjective"},
        {"position": 7, "type": "noun"},
        {"position": 8, "type": "verb-ending-in-ing"},
        {"position": 9, "type": "body-part"},
        {"position": 10, "type": "verb"},
        {"position": 11, "type": "adjective"},
        {"position": 12, "type": "noun-plural"}
      ]
    }',
    'superhero',
    true
  ),
  (
    'The Jungle Expedition',
    '{
      "story": "Explorer {0} searched for the legendary {1} ruins in the jungles of {2}. Armed with a {3} {4} and {5} {6}, they discovered a {7} temple guarded by {8} {9}. Inside was a golden {10} that could {11} when touched! The temple started collapsing so {0} had to escape with the treasure!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "noun-place-name"},
        {"position": 3, "type": "color"},
        {"position": 4, "type": "noun"},
        {"position": 5, "type": "number"},
        {"position": 6, "type": "noun-plural"},
        {"position": 7, "type": "adjective"},
        {"position": 8, "type": "number"},
        {"position": 9, "type": "animal"},
        {"position": 10, "type": "noun"},
        {"position": 11, "type": "verb"}
      ]
    }',
    'adventure',
    true
  ),
  (
    'The Mountain Climb',
    '{
      "story": "I climbed Mount {0}, the most {1} peak in {2}. My guide {3} said to bring {4} layers of clothing and {5} {6} for energy. On day {7} a {8} storm hit and we had to hide in a cave. When we reached the summit, the view was so {9} that I started {10}. On the way down, I slipped and slid {11} feet!",
      "placeholders": [
        {"position": 0, "type": "noun-place-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "noun-place-name"},
        {"position": 3, "type": "noun-person-name"},
        {"position": 4, "type": "number"},
        {"position": 5, "type": "adjective"},
        {"position": 6, "type": "food"},
        {"position": 7, "type": "number"},
        {"position": 8, "type": "adjective"},
        {"position": 9, "type": "adjective"},
        {"position": 10, "type": "verb-ending-in-ing"},
        {"position": 11, "type": "number"}
      ]
    }',
    'adventure',
    true
  ),
  (
    'The Homework Disaster',
    '{
      "story": "I had {0} hours to finish my {1} homework for {2}''s class. I got distracted when my pet {3} started {4} on my papers. By {5} o''clock, I quickly wrote {6} pages in {7} minutes. When I turned it in, {2}''s {8} turned {9} because I had written about {10} {11} instead!",
      "placeholders": [
        {"position": 0, "type": "number"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "noun-person-name"},
        {"position": 3, "type": "animal"},
        {"position": 4, "type": "verb-ending-in-ing"},
        {"position": 5, "type": "number"},
        {"position": 6, "type": "number"},
        {"position": 7, "type": "number"},
        {"position": 8, "type": "body-part"},
        {"position": 9, "type": "color"},
        {"position": 10, "type": "color"},
        {"position": 11, "type": "animal"}
      ]
    }',
    'school',
    true
  ),
  (
    'The School Play',
    '{
      "story": "Our school put on a play called ''{0} in {1}''. I was cast as a {2} {3} who had to {4} in every scene. On opening night, my {5} {6} costume ripped! I improvised with {7} {8} from the prop closet. During the big scene, {9} forgot their lines and started {10} instead. The {11} {12} we used as a prop came alive!",
      "placeholders": [
        {"position": 0, "type": "noun"},
        {"position": 1, "type": "noun-place-name"},
        {"position": 2, "type": "adjective"},
        {"position": 3, "type": "animal"},
        {"position": 4, "type": "verb"},
        {"position": 5, "type": "color"},
        {"position": 6, "type": "noun-plural"},
        {"position": 7, "type": "adjective"},
        {"position": 8, "type": "noun-plural"},
        {"position": 9, "type": "noun-person-name"},
        {"position": 10, "type": "verb-ending-in-ing"},
        {"position": 11, "type": "color"},
        {"position": 12, "type": "animal"}
      ]
    }',
    'school',
    true
  ),
  (
    'The Restaurant Opening',
    '{
      "story": "My friend {0} opened a restaurant called ''{1} {2}''. Their signature dish was {3} {4} with {5} {6}. The first customer ordered {7} portions! The oven started {8} and turned everything {9}. A food critic said it tasted like {10}. The restaurant closed after {11} days!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "noun"},
        {"position": 3, "type": "adjective"},
        {"position": 4, "type": "food"},
        {"position": 5, "type": "color"},
        {"position": 6, "type": "food"},
        {"position": 7, "type": "number"},
        {"position": 8, "type": "verb-ending-in-ing"},
        {"position": 9, "type": "color"},
        {"position": 10, "type": "noun-plural"},
        {"position": 11, "type": "number"}
      ]
    }',
    'cooking',
    true
  ),
  (
    'The Cooking Class',
    '{
      "story": "I took a cooking class taught by Chef {0}. We learned to make {1} {2}. When it was my turn, I accidentally used {3} cups of salt instead of {4}! My dish turned {5} and started {6}. My partner {7} tried to help by adding {8} {9}, but that made it worse. For the final exam, I made {10} that actually tasted {11}!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "adjective"},
        {"position": 2, "type": "food"},
        {"position": 3, "type": "number"},
        {"position": 4, "type": "number"},
        {"position": 5, "type": "color"},
        {"position": 6, "type": "verb-ending-in-ing"},
        {"position": 7, "type": "noun-person-name"},
        {"position": 8, "type": "adjective"},
        {"position": 9, "type": "food"},
        {"position": 10, "type": "food"},
        {"position": 11, "type": "adjective"}
      ]
    }',
    'cooking',
    true
  ),
  (
    'The Pet Show',
    '{
      "story": "I entered my {0} {1} named {2} in the pet show. For the talent portion, {2} had to {3} while balancing {4} {5} on its {6}. Judge {7} gave us a score of {8}. In the costume contest, I dressed {2} as a {9} {10} with a {11} cape. We didn''t win, but {2} did {12} on the judge''s {13}!",
      "placeholders": [
        {"position": 0, "type": "color"},
        {"position": 1, "type": "animal"},
        {"position": 2, "type": "noun-person-name"},
        {"position": 3, "type": "verb"},
        {"position": 4, "type": "number"},
        {"position": 5, "type": "noun-plural"},
        {"position": 6, "type": "body-part"},
        {"position": 7, "type": "noun-person-name"},
        {"position": 8, "type": "number"},
        {"position": 9, "type": "adjective"},
        {"position": 10, "type": "noun"},
        {"position": 11, "type": "color"},
        {"position": 12, "type": "verb"},
        {"position": 13, "type": "body-part"}
      ]
    }',
    'pets',
    true
  ),
  (
    'The Pet Sitter',
    '{
      "story": "I pet-sat for my neighbor {0} who went to {1} for {2} days. They left me {3} {4} that lived in a {5} {6}. The instructions said to feed them {7} {8} every {9} hours. On day one, I messed up and they escaped! I found them {10} in the {11} {12}. When {0} came back, their pets looked {13}!",
      "placeholders": [
        {"position": 0, "type": "noun-person-name"},
        {"position": 1, "type": "noun-place-name"},
        {"position": 2, "type": "number"},
        {"position": 3, "type": "number"},
        {"position": 4, "type": "animal"},
        {"position": 5, "type": "adjective"},
        {"position": 6, "type": "noun"},
        {"position": 7, "type": "color"},
        {"position": 8, "type": "food"},
        {"position": 9, "type": "number"},
        {"position": 10, "type": "verb-ending-in-ing"},
        {"position": 11, "type": "adjective"},
        {"position": 12, "type": "noun"},
        {"position": 13, "type": "adjective"}
      ]
    }',
    'pets',
    true
  );
